<?php
/**
 * @file
 * Code for the Youtube Playlists feature.
 */

include_once 'youtube_playlists.features.inc';

/**
 * Assigns videos to playlist from XML file
 *
 * Only updates videos that have been changed.
 * Removed current playlist assignments for video if it is no longer assigned.
 */
function _youtube_playlists_assign_videos() {
  $new_video_assignments = _youtube_playlists_get_new_assignments();
  if ($new_video_assignments) {
    $current_video_assignments = _youtube_playlist_get_current_assignments();
    _youtube_playlists_save_new_assignments($new_video_assignments, $current_video_assignments);
    _youtube_playlists_save_videos_no_playlists($current_video_assignments, $new_video_assignments);
  }
}

/**
 * Retrieve video relationships.
 * @return array();
 *  Indexed array where values are arrays with values:
 *  - video_id
 *  - playlist_id
 */
function _youtube_playlists_retrieve_playlist_video_relationships() {
  $assignments_url = variable_get('youtube_playlists_assignments_url', FALSE);
  if (!$assignments_url) {
    watchdog('youtube_playlists', 'Error youtube_playlists_assignments_url variable not set.', WATCHDOG_ERROR);
    return array();
  }
  $response = drupal_http_request($assignments_url);
  if ($response->error) {
    watchdog('youtube_playlists', 'Error retrieving feed: @msg', array('@msg' => $response->error), WATCHDOG_ERROR);
    return array();
  }
  $xml = simplexml_load_string($response->data);
  $relationships = array();
  foreach ($xml->entries->videoinplaylist as $video_assignment) {
    $relationships[] = array(
      'video_id' => (string) $video_assignment->videoId,
      'playlist_id' => (string) $video_assignment->playlistId,
    );
  }
  return $relationships;
}

/**
 * Remove playlists from
 * @param $current_video_assignments
 * @param $new_video_assignments
 */
function _youtube_playlists_save_videos_no_playlists($current_video_assignments, $new_video_assignments) {
// Remove any video that aren't in assignments but were in current
  $unassigned_video_nids = array_keys(array_diff_key($current_video_assignments, $new_video_assignments));
  if ($unassigned_video_nids) {
    $playlist_tids = _youtube_playlists_get_playlist_tids();
    foreach ($unassigned_video_nids as $video_nid) {
      $video_wrapper = entity_metadata_wrapper('node', $video_nid);
      $all_tids = $video_wrapper->field_tags->raw();
      // Remove all playlist tids.
      $tids_without_playlists = array_diff($all_tids, $playlist_tids);
      $video_wrapper->field_tags->set($tids_without_playlists);
      $video_wrapper->save();
    }
  }
}

/**
 * Save all video assignments that assignments that are different from current assignments.
 * @param $new_video_assignments
 *  An associative array whose keys are the Video nids and values are array of playlist term tids.
 * @param $current_video_assignments
 *  An associative array whose keys are the Video nids and values are array of playlist term tids.
 */
function _youtube_playlists_save_new_assignments($new_video_assignments, $current_video_assignments) {
  $playlist_tids = _youtube_playlists_get_playlist_tids();
  // Loop through new assignments and update only need ones. Saves calls to node_save.
  foreach ($new_video_assignments as $video_nid => $new_video_assignment) {
    // If the video is not currently assigned to a playlists needs to be assigned
    $needs_update = !isset($current_video_assignments[$video_nid]);
    if (!$needs_update) {
      sort($new_video_assignment);
      sort($current_video_assignments[$video_nid]);
      $needs_update = $new_video_assignment != $current_video_assignments[$video_nid];
    }
    if ($needs_update) {
      // Update Video playlist assignment
      $video_wrapper = entity_metadata_wrapper('node', $video_nid);
      $all_tids = $video_wrapper->field_tags->raw();
      $non_playlist_tids = array_diff($all_tids, $playlist_tids);
      $new_tids = array_merge($non_playlist_tids, $new_video_assignment);
      $video_wrapper->field_tags->set($new_tids);
      $video_wrapper->save();
    }
  }
}

/**
 * Get all playlist term tids
 * @return array
 *  Playlist term tids
 */
function _youtube_playlists_get_playlist_tids(){
  $tids = & drupal_static(__FUNCTION__);
  if (!isset($tids)) {
    $sql = 'SELECT tid FROM {taxonomy_term_data} WHERE  name LIKE  \'YT-%\'';
    $tids = db_query($sql)->fetchCol();
  }
  return $tids;

}
/**
 * Returns new video playlist assignments.
 * @return array
 *  An associative array whose keys are the Video nids and values are array of playlist term tids.
 */
function _youtube_playlists_get_new_assignments() {
  $playlist_videos_relationships = _youtube_playlists_retrieve_playlist_video_relationships();
  $new_video_assignments = array();
  $unknown_videos = array();
  $unknown_playlists = array();
  foreach ($playlist_videos_relationships as $playlist_videos_relationship) {
    $video_nid = youtube_videos_get_nid_from_video_id($playlist_videos_relationship['video_id']);
    $playlist_tid = _youtube_playlists_get_tid_from_playlist_id($playlist_videos_relationship['playlist_id']);
    // Keep of list of videos and playlists that aren't nodes.
    if (!$video_nid) {
      $unknown_videos[] = (string) $playlist_videos_relationship->videoId;
    }
    if (!$playlist_tid) {
      $unknown_playlists[] = (string) $playlist_videos_relationship->playlistId;
    }
    if ($video_nid && $playlist_tid) {
      // Both the video and playlist were found.
      // Check that playlist is not already set(duplicate entries in assignment xml).
      if (empty($new_video_assignments[$video_nid]) || !in_array($playlist_tid, $new_video_assignments[$video_nid])) {
        $new_video_assignments[$video_nid][] = $playlist_tid;
      }

    }
  }
  if ($unknown_videos) {
    watchdog('youtube_playlists', 'Unknown video were found during playlist assignment. @video_ids', array('@video_ids' => implode(',', $unknown_videos)), WATCHDOG_WARNING);
  }
  if ($unknown_playlists) {
    watchdog('youtube_playlists', 'Unknown playlists were found during playlist assignment. @playlist_ids', array('@playlist_ids' => implode(',', $unknown_playlists)), WATCHDOG_WARNING);
  }
  return $new_video_assignments;
}

/**
 * Gets the nid for youtube Playlist id
 * @param $playlist_id
 * @return int | NULL
 */
function _youtube_playlists_get_tid_from_playlist_id($playlist_id) {
  module_load_include('inc', 'feeds', 'mappers/taxonomy');
  $tids = & drupal_static(__FUNCTION__);
  if (!isset($tids)) {
    $tids = array();
  }
  else {
    if (isset($tids[$playlist_id])) {
      return $tids[$playlist_id];
    }
  }
  $tids[$playlist_id] = taxonomy_feeds_term_lookup_term_by_guid($playlist_id);

  return $tids[$playlist_id];
}

/**
 * Get current Video playlist assignments.
 * @return array
 *  An associative array whose keys are the Video nids and values are array of playlist term tids.
 */
function _youtube_playlist_get_current_assignments() {
  $video_assignments = array();
  $sql = 'SELECT ti.tid as tid, ti.nid as nid FROM {taxonomy_index} ti'
    . ' inner join taxonomy_term_data td on ti.tid = td.tid'
    . ' where name like \'YT-%\'';
  $result = db_query($sql);

  while ($record = $result->fetchAssoc()) {
    $video_assignments[$record['nid']][] = $record['tid'];
  }
  return $video_assignments;
}

/**
 * Implements hook_playlist_feeds_after_import().
 *
 * Import Playlists after Videos.
 * 
 * Assign Videos to Playlists after imported.
 */
function youtube_playlists_feeds_after_import(FeedsSource $source) {
  if ($source->importer->id == 'youtube_importer') {
    // Run Youtube Playlist importer automatically as soon as Youtube Video importer runs.
    $source = feeds_source('youtube_playlist_tag_importer');
    if ($source) {
      $source->startImport();
    }
  }
  if ($source->importer->id == 'youtube_playlist_tag_importer') {
    // After Youtube Playlist import runs assign videos to playlists.
    _youtube_playlists_assign_videos();
  }
}