<?php
/**
 * @file
 * Code for the ILR Certificate Programs feature.
 */

include_once 'ilr_certificate_programs.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function ilr_certificate_programs_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['alternate_teaser'] = array(
    'label' => t('Alternate teaser'),
    'custom settings' => FALSE,
  );
}

/**
 * Implements hook_node_view().
 * Adds Javascript for core curriculum list's accordian behavior.
 */
function ilr_certificate_programs_node_view($node, $view_mode, $langcode) {
  if($node->type == 'certificate_programs' && $view_mode == 'full') {
    drupal_add_js(drupal_get_path('module','ilr_certificate_programs') . '/ilr_certificate_programs.js', array('type' => 'file', 'scope' => 'footer'));
  }
}

/**
 * Implements hook_preprocess_node
 * Groups title and field_value_propostiions together in featured region.
 */
function ilr_certificate_programs_preprocess_node(&$variables) {
  if($variables['type'] == 'certificate_programs' && $variables['view_mode'] == 'ilr_theme__highlighted') {
    $wrapper = ilr_get_node_wrapper($variables['node']);
    $title = $wrapper->title->value();
    $variables['content']['field_image']['#weight'] = 0;
    $variables['content']['title'] = array('#markup'=>"<div class='pitch'><h1>$title</h1>", '#weight'=>1);
    $variables['content']['field_value_propositions']['#weight'] = 2;
    $variables['content']['title_close'] = array('#markup'=>"</div>", '#weight'=>10);
  }
}
