<?php
/**
 * @file
 * Code for the ILR Certificate Programs feature.
 */

include_once 'ilr_certificate_programs.features.inc';

/**
 * Implements hook_preprocess_node
 */
function ilr_certificate_programs_preprocess_node(&$variables) {
  if ($variables['type'] == 'certificate_programs' &&
      $variables['view_mode'] == 'full') {
    $wrapper = ilr_get_node_wrapper($variables['node']);
    $title = $wrapper->title->value();
    $description = $wrapper->field_description_long->value();
    $descr_value = $description['value'];

    $markup = "<h1 class='title'>$title</h1>$descr_value";
    $variables['content']['field_description_long'][0]['#markup'] = $markup;
  }
}
