<?php

/**
 * Implements hook_preprocess_html().
 * Adds "microsite" class to the body tag
 */
function microsite_nav_preprocess_html(&$variables) {
  if (_microsite_nav_is_microsite()) {
    $variables['classes_array'][] = 'microsite';
  }
}

/**
 * Implements hook_block_view_alter().
 * Checks to see if the current page is a microsite.
 * Removes the menu items if so,
 * allowing microsite_nav.js to build the menu.
 */
function microsite_nav_block_view_alter(&$data, $block) {
  if ($block->module == 'ilr_mega_menu') {
    if (_microsite_nav_is_microsite()) {
      $data['content'] = '<div class="menu-block-ilr-primary-menu"><ul class="menu"></ul></div>';
    }
  }
}

/**
 * Implements hook_node_view().
 */
function microsite_nav_node_view($node, $view_mode, $langcode) {
  if ($view_mode == 'full' && !empty($node->microsite)) {
    drupal_add_js(drupal_get_path('module','microsite_nav') . '/microsite_nav.js', array('type' => 'file', 'scope' => 'footer'));
  }
}

function _microsite_nav_is_microsite() {
  if ($node = menu_get_object()) {
    return $node->microsite;
  }
  return FALSE;
}

