<?php

/**
 * Implements hook_block_info().
 * Adds the google translate block
 */
function ilr_google_translate_block_info() {
  $blocks['google_translate'] = array(
    'info' => t('Google Translate'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ilr_google_translate_block_view($delta='') {
  if ($delta == 'google_translate') {
    $languages = array(
      'French' => array('pair' => 'en|fr', 'title' => 'Francais/French'),
      'German' => array('pair' => 'en|de', 'title' => 'Deutsch/German'),
      'Italian' => array('pair' => 'en|it', 'title' => 'Italiano/Italian'),
      'Portuguese' => array('pair' => 'en|pt', 'title' => 'Portugues/Portuguese'),
      'Spanish' => array('pair' => 'en|es', 'title' => 'Espanol/Spanish'),
      'Japanese' => array('pair' => 'en|ja', 'title' => 'Japanese'),
      'Korean' => array('pair' => 'en|ko', 'title' => 'Korean'),
      'Chinese' => array('pair' => 'en|zh-CN', 'title' => 'Chinese'),
      'Czech' => array('pair' => 'en|cs', 'title' => 'Czech'),
      'Arabic' => array('pair' => 'en|ar', 'title' => 'Arabic'),
    );
    $image_path = drupal_get_path('theme', 'ilr_theme') . '/images/transparent.gif';
    $markup = '<div id="translate">
      <form action="http://www.google.com/translate" id="google-translation">
    ';

    foreach ($languages as $name => $values) {
      $markup .= '    <input value="'. $values['pair'] .'" title="'.$values['title'].'" alt="'.$name.'" type="image" class="flag '.$name.'" src="/'.$image_path.'" />';
    }

    $markup .= '    <input name="hl" value="en" type="hidden" />
      <input name="ie" value="UTF8" type="hidden" />
      <input name="langpair" value="" type="hidden" />
    </form>';

    $block = array(
      'subject' => '',
      'content' => $markup,
    );
  }
  return $block;
}
