<?php
/**
 * @file
 */

/**
 * Implements hook_init()
 *
 * Adds the livereload javascript so we don't need the browser extension.
 */
function drupal_streamline_dev_init() {
  // gulp-livereload includes a copy of the livereload.js script at the same
  // port configured in the gulpfile.
  // Other livereload options available: &mindelay=1000&maxdelay=60000
  $livereload_js_uri = 'http://localhost:35777/livereload.js?host=localhost&port=35777&snipver=1';
  drupal_add_js($livereload_js_uri, array('type' => 'external', 'scope' => 'footer'));
}

/**
 * Implements hook_custom_theme()
 */
function drupal_streamline_dev_custom_theme() {
  // Allow the user to request a particular theme via a query parameter.
  if (isset($_GET['theme'])) {
    return $_GET['theme'];
  }
}

/**
 * Implements hook_css_alter().
 *
 * Force CSS to be added with link tags, rather than @import. Makes livereload work better.
 */
function drupal_streamline_dev_css_alter(&$css) {
  foreach ($css as $key => $value) {
    $css[$key]['preprocess'] = FALSE;
  }
}
