<?php

/**
 * Implements hook_enable()
 */
function drupal_streamline_dev_enable() {
  // Set local error reporting
  variable_set('error_level', ERROR_REPORTING_DISPLAY_ALL);

  // Set tmp directory for Vagrant
  variable_set('file_temporary_path','/tmp');
}

/**
 * Implements hook_disable()
 */
function drupal_streamline_dev_disable() {
  // Stop redirecting all outgoing mail
  variable_set('mail_system', array('default-system' => 'DefaultMailSystem'));
}
