<?php
/**
 * @file
 * Code for the ILR Reflection feature.
 */

include_once 'ilr_reflection.features.inc';

function ilr_reflection_block_info() {
  $blocks['reflection_node_form'] = array(
    'info' => t('Add a reflection'),
  );
  return $blocks;
}

function ilr_reflection_block_view($delta = ''){
  $block = array();

  switch ($delta) {
    case 'reflection_node_form':
      module_load_include('inc', 'node', 'node.pages');
      $title = drupal_get_title(); // Store the original title
      $form = node_add('reflection');
      drupal_set_title($title, PASS_THROUGH); // Restore the original title
      $block['subject'] = t('Share a Memory');
      $block['content']['form'] = $form;

      // Hide the vertical tabs in the block version
      $tabs = array('revision_information','author','options','menu','path');
      foreach ($tabs as $key => $name) {
        if (isset($form[$name])) {
          $form[$name]['#access'] = false;
        }
      }

  }

  return $block;
}

/**
 * Implements hook_node_view().
 * Calls required formatting function(s) for reflections
 */
function ilr_reflection_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'reflection' && $view_mode == 'teaser') {
    _ilr_reflection_format_class_year($node);
    _ilr_reflection_add_social_sharing($node);
  }
}

/**
 * Implements hook_form_alter().
 * Removes the youtube_video field for most roles
 */
function ilr_reflection_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'reflection_node_form') {
    // Remove editing the profile type except for admins
    if (!_ilr_user_has_role(array('administrator','contributor'))) {
      $form['field_youtube_video']['#access'] = FALSE;
      $form['field_tags']['#access'] = FALSE;
    }
  }
}

/**
 * Returns the last two digits of the class year
 * prepended with an apostrophe
 */
function _ilr_reflection_add_social_sharing(&$node) {
  $channels = array('twitter','facebook','linkedin','email');
  $markup = '<ul class="social">';
  foreach ($channels as $key => $channel) {
    $markup .= "  <li><a class='$channel' href='#'>$channel</a></li>\n";
  }
  $markup .= '</ul>';
  $node->content['social_links']['#markup'] = $markup;
}

/**
 * Returns the last two digits of the class year
 * prepended with an apostrophe
 */
function _ilr_reflection_format_class_year(&$node) {
  if (count($node->field_year_as_list_text)) {
    $year = $node->content['field_year_as_list_text'][0]['#markup'];
    $node->content['field_year_as_list_text'][0]['#markup'] = "'" . substr($year, -2);
  }
}
