<?php

/**
 * @file
 * Code for the ILR Accessibility feature.
 */

include_once 'ilr_accessibility.features.inc';

/**
 * Implements hook_menu().
 */
function ilr_accessibility_menu() {
  $items['download/%file'] = [
    'page callback' => 'ilr_accessibility_download',
    'page arguments' => [1],
    'title callback' => 'ilr_accessibility_download_title',
    'title arguments' => [1],
    'access arguments' => ['access content'],
  ];

  return $items;
}

/**
 * Page callback for `download/%file`.
 */
function ilr_accessibility_download($file) {
  $output = '';
  $url = file_create_url($file->uri);

  // Set options as per anchor format described at
  // http://microformats.org/wiki/file-format-examples
  $options = array(
    'attributes' => array(
      'type' => $file->filemime . '; length=' . $file->filesize,
      'class' => 'button button-info'
    ),
  );

  $output .= '<div>' . t('If you have difficulty accessing the information contained in this document, please contact us at <a href="mailto:access-ilr@cornell.edu">access-ilr@cornell.edu</a> and we will assist you.') . '</div>';

  $output .= '<p>' . l('Download', $url, $options) . '</p>';

  return $output;
}

/**
 * Title callback for `download/%file`.
 */
function ilr_accessibility_download_title($file) {
  // Use the description as the link text if available.
  return empty($file->description) ? $file->filename : $file->description;
}

/**
 * Implements hook_permission().
 */
function ilr_accessibility_permission() {
  return [
    'edit field accessible' => [
      'title' => t('Edit Accessilble Field'),
    ],
  ];
}

/**
 * Implements hook_field_access().
 */
function ilr_accessibility_field_access($op, $field, $entity_type, $entity = NULL, $account = NULL) {
  if ($field['field_name'] === 'field_accessible' && $op === 'edit') {
    return user_access('edit field accessible', $account);
  }

  return TRUE;
}

/**
 * Implements hook_page_alter().
 */
function ilr_accessibility_page_alter(&$page) {
  if (!ilr_accessibility_is_pdf_hostname()) {
    return;
  }

  // Remove mega menu, footer menus, and secondary menu.
  unset($page['header']['ilr_mega_menu_ilr_mega_menu']);
  unset($page["sidebar_first"]["menu_block_ilr-subnav"]);
  unset($page["footer"]["bean_footer-links"]);
  unset($page["footer"]["bean_footer-links-2"]);
  unset($page["footer"]["bean_footer-social"]);
}

/**
 * Implements template_preprocess_page().
 */
function ilr_accessibility_preprocess_page(&$variables) {
  if (!ilr_accessibility_is_pdf_hostname()) {
    return;
  }

  $variables['is_pdf_host'] = TRUE;
}

/**
 * Helper function to determine if the current hostname is the alternate
 * download one.
 */
function ilr_accessibility_is_pdf_hostname() {
  return $GLOBALS['base_url'] === variable_get('ilr_accessibility_pdf_hostname', 'https://archive.ilr.cornell.edu');
}
