<?php
/**
 * @file
 * Code for the Universal Google Analytics Implementation
 */

/**
 * Implements hook_page_alter()
 * Modified from the Google Analytics module
 *
 */
function fullstory_page_alter(&$page) {
  global $user;

  if (!ilr_is_production_site()) { // Don't track
    return;
  }

  // Track page views if user not logged in
  if (($user->uid < 1)) {
    // Build fullstory code.
    $script = "window['_fs_debug'] = false; window['_fs_host'] = 'fullstory.com';";
    $script .= " window['_fs_org'] = 'FVH85'; window['_fs_namespace'] = 'FS';";
    $script .= " (function(m,n,e,t,l,o,g,y){ if (e in m) {if(m.console && m.console.log) { m.console.log('FullStory namespace conflict. Please set window[\"_fs_namespace\"].');} return;}";
    $script .= " g=m[e]=function(a,b,s){g.q?g.q.push([a,b,s]):g._api(a,b,s);};g.q=[];";
    $script .= " o=n.createElement(t);o.async=1;o.src='https://'+_fs_host+'/s/fs.js';";
    $script .= " y=n.getElementsByTagName(t)[0];y.parentNode.insertBefore(o,y);";
    $script .= " g.identify=function(i,v,s){g(l,{uid:i},s);if(v)g(l,v,s)};g.setUserVars=function(v,s){g(l,v,s)};";
    $script .= "g.event=function(i,v,s){g('event',{n:i,p:v},s)};";
    $script .= " g.shutdown=function(){g(\"rec\",!1)};g.restart=function(){g(\"rec\",!0)}; g.consent=function(a){g(\"consent\",!arguments.length||a)};";
    $script .= " g.identifyAccount=function(i,v){o='account';v=v||{};v.acctId=i;g(o,v)}; g.clearUserCookie=function(){}; })(window,document,window['_fs_namespace'],'script','user');";

    drupal_add_js($script, array('scope' => 'header', 'type' => 'inline'));
  }
}
