<?php

/**
 * Removes entityform type fex_wisp_student_application from ilr_forms_students feature
 */
function ilr_forms_students_update_7001() {
  if ($entityform_type = entityform_type_load('fex_wisp_student_application')) {
    entityform_type_delete($entityform_type);
  }
}

/**
 * Delete entityform submissions for fex_wisp_sponsor_registration
 */
function ilr_forms_students_update_7002() {
  _forms_delete_entityform_submissions('fex_wisp_sponsor_registration');
}

