<?php
/**
 * @file
 * Code for the Featured Book feature.
 */

include_once 'featured_book.features.inc';

define('LIBRARY_CATALOG_LINK', 'http://newcatalog.library.cornell.edu/?search_field=title&q=');

/**
 * Implements hook_preprocess_hook()
 * Adds the publication info to the end of the body text
 */
function featured_book_preprocess_node(&$variables) {
  if ($variables['type'] == 'featured_book') {
    $href = _featured_book_get_catalog_link($variables);
    $variables['node_url'] = $href;
    $variables['content']['body'][0]['#markup'] .= _featured_book_create_publication_info($variables, $href);
    if (count($variables['field_thumbnail'])) {
      $variables['content']['field_thumbnail'][0]['#path']['path'] = $href;
    }
  }
}

/**
 * Creates the publication info markup
 */
function _featured_book_create_publication_info($variables, $href) {
  $markup = '<p>';
  $markup .= $variables['field_city'][LANGUAGE_NONE][0]['value'] . ': ';
  $markup .= $variables['field_publisher'][LANGUAGE_NONE][0]['value'] . '. ';
  $markup .= $variables['field_featured_book_pages'][LANGUAGE_NONE][0]['value'] . ' pages<br />';
  $call = $variables['field_call_number'][LANGUAGE_NONE][0]['value'];
  $isbn = $variables['field_isbn'][LANGUAGE_NONE][0]['value'];
  $markup .= "ISBN $isbn ";
  $markup .= '<a href="$href">' . $call . '</a></p>';
  return $markup;
}

function _featured_book_get_catalog_link($variables) {
  $query_string = str_replace(' ', '+', $variables['title']);
  return LIBRARY_CATALOG_LINK . $query_string;
}
