<?php

/**
 * Implements hook_page_build().
 */
function ilr_at_70_page_build(&$page) {
  if (isset($page['header']) && $node = menu_get_object()) {
    if ($node->title == 'ILR at 70') {
      $nav = array(
        'ilr_at_70_nav' => array(
          '#markup' => _ilr_at_70_get_nav_markup(),
        ),
      );

      if (isset($page['header']['ilr_mega_menu_ilr_mega_menu'])) {
        unset($page['header']['ilr_mega_menu_ilr_mega_menu']);
      }
      $page['header'] = $nav + $page['header'];

      // Add the js
      drupal_add_js(array(
        'ilr_social_sharing' => array(
          'hashtags' => array('ILR70'),
          'emailSubjectPrefix' => 'ILR at 70',
        ),
      ), 'setting');
    }
  }
}

/**
 * Implements hook_preprocess().
 * Adds social buttons to reflection teasers
 */
function ilr_at_70_preprocess_node(&$variables) {
  if ($variables['type'] == 'reflection') {
    if ($variables['view_mode'] == 'teaser') {
      _ilr_social_sharing_add_social_buttons($variables);

      if (_ilr_at_70_node_is_truncated($variables)) {
        ilr_add_read_more_link($variables);
      }
    }
    if (_ilr_at_70_is_quote($variables['node'])) {
      $variables['classes_array'][] = 'quote';
    }
  }
}

/**
 * Somewhat hacky way to figure out whether the node has a longer version
 */
function _ilr_at_70_node_is_truncated($variables) {
  $wrapper = ilr_get_node_wrapper($variables['node']);
  $body_array = $wrapper->body->value();
  $full_body = $body_array['value'];
  return strlen($full_body) - strlen($variables['content']['body'][0]['#markup']) > 10;
}

/**
 * Checks for a "quote"
 * Contributors will simply need to make the body text "quote"
 * for a given item to display as a quote
 */
function _ilr_at_70_is_quote($node) {
  return $node->title == 'quote';
}

function _ilr_at_70_get_nav_markup() {
  $markup = '';
  if ($bean = bean_load_delta('ilr-at-70-nav')) {
    $markup = $bean->field_bean_content[LANGUAGE_NONE][0]['value'];
  }
  return $markup;
}
