<?php

/**
 * @file
 * basic_page.features.filter.inc
 */

/**
 * Implements hook_filter_default_formats().
 */
function basic_page_filter_default_formats() {
  $formats = array();

  // Exported format: Full HTML.
  $formats['full_html'] = array(
    'format' => 'full_html',
    'name' => 'Full HTML',
    'cache' => 0,
    'status' => 1,
    'weight' => 0,
    'filters' => array(
      'ckeditor_link_filter' => array(
        'weight' => 0,
        'status' => 1,
        'settings' => array(),
      ),
      'insert_block' => array(
        'weight' => 2,
        'status' => 1,
        'settings' => array(
          'check_roles' => 0,
        ),
      ),
      'media_filter' => array(
        'weight' => 2,
        'status' => 1,
        'settings' => array(),
      ),
    ),
  );

  return $formats;
}
