<?php
/**
 * @file
 * Code for the Basic Page feature.
 */

include_once 'basic_page.features.inc';

/**
 * Implements hook_init().
 */
function basic_page_init() {
  drupal_add_js(drupal_get_path('module','basic_page') . '/basic_page.js', array('type' => 'file', 'scope' => 'footer'));
}


/**
 * Implements hook_form_alter().
 * Adds the editor notes tab to the basic page fieldsets.
 */
function basic_page_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'basic_page_node_form') {
    $form['editor_notes'] = array(
      '#type' => 'fieldset',
      '#title' => t('Editor Notes'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#weight' => 10,
      '#group' => 'additional_settings',
    );
    $form['editor_notes']['field_editor_notes'] = $form['field_editor_notes'];
    unset($form['field_editor_notes']);
  }

  return $form;
}
