<?php
/**
 * @file
 * Code for the Basic Page feature.
 */

include_once 'basic_page.features.inc';

/**
 * Implements hook_init().
 */
function basic_page_init() {
  global $theme;
  if ($theme == 'ilr_theme') {
    drupal_add_js(drupal_get_path('module','basic_page') . '/basic_page.js', array('type' => 'file', 'scope' => 'footer'));
  }

}

function basic_page_node_access($node, $op, $account) {
  if ($op == 'view' && isset($node->kerberized) && $node->kerberized) {
    if (!ilr_user_has_netid()) {
      drupal_set_message('You must be logged in with your NetID to access this page. <a href="/saml_login">Login here.</a>', 'warning');
      return NODE_ACCESS_DENY;
    }
  }
}

/**
 * Implements hook_form_alter().
 * Adds the editor notes tab to the basic page fieldsets.
 */
function basic_page_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'basic_page_node_form') {
    $form['editor_notes'] = array(
      '#type' => 'fieldset',
      '#title' => t('Editor Notes'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#weight' => 10,
      '#group' => 'additional_settings',
    );
    $form['editor_notes']['field_editor_notes'] = $form['field_editor_notes'];
    unset($form['field_editor_notes']);
  }

  return $form;
}

/**
* Implements hook_admin_menu_output_build().
* Adds the editor notes items to the menu.
*/
function basic_page_admin_menu_output_build(&$content) {
  if (isset($content['menu']) && module_exists('editor_note') && user_access('edit any basic_page content')) {
    $content['menu']['admin/content']['admin/content/editor-notes'] = array(
      '#title' => t('Editor Notes'),
      '#href' => 'admin/content/editor-notes',
      '#options' => array(
        'access callback' => 'user_access',
        'access arguments' => array(''),
      ),
      // #weight controls the order of links in the resulting item list.
      '#weight' => 50,
    );

    if ($netid = ilr_get_netid_of_current_user()) {
      $content['menu']['admin/content']['admin/content/editor-notes']['admin/content/editor-notes/notes-for-me'] = array(
        '#title' => t('Notes for me'),
        '#href' => 'admin/content/editor-notes',
        '#options' => array(
          'query' => array('note' => $netid),
        ),
      );
    }
  }
}
