<?php
/**
 * @file ilr_legacy_redirect.module
 * Contains code to run imports.
 *
 * Module should be disabled after imports are run.
 * Redirect files are in migration_data/redirects
/**
 * Runs all imports.
 *
 * Is called from ilr_legacy_redirect_install.
 * Also can be called locally from drush via php-eval
 */
function ilr_legacy_redirect_run_imports() {
  $messages = array();
  _ilr_legacy_redirect_news();
  _ilr_legacy_redirect_sdc();
}

function _ilr_legacy_redirect_sdc() {
  $redirect_sdc = new ILRRedirectSDCLoader('sdc-course-redirects.csv');
  $redirect_sdc->runImport();
}

function _ilr_legacy_redirect_news() {
  $redirect_news = new ILRRedirectMigrationLoader('news-redirects.csv', 'news');
  $redirect_news->runImport();
}


