<?php

function cul_search_block_info() {
  $blocks['cul_catalog_search'] = array(
    'info' => t('Cornell University Library Catalog Search'),
  );
  return $blocks;
}

function cul_search_block_view($delta='cul_catalog_search') {
  drupal_add_js(drupal_get_path('module','cul_search') . '/cul_search.js', array('type' => 'file', 'scope' => 'footer'));

  $generator = _cul_search_generate_markup();
  $block = array(
    'subject' => 'Cornell University Library Catalog Search',
    'content' => $generator,
  );
  return $block;
}

/**
 * Generates the markup for the search form
 */
function _cul_search_generate_markup() {
  $markup = <<<EOT
<section class="search-home">
  <!-- Pay attention to METHOD -->
  <form id="search" name="form1" method="get" action="https://search.library.cornell.edu">
    <label for="name">Search <span class="search-filter-selected">Library</span></label>
    <div class="filtered-search">
      <input type="text" class="search-homepage" name="q" value="" id="edit_keys" placeholder="Search all Cornell University Library resources">

      <!--<select name="search_type" id="search_type" size="1" onChange="chgAction()" class="form-control filter">
        <option value="catalog" selected="selected">Library Catalog</option>
        <option value="worldcat">WorldCat</option>
        <option value="site">Site Search</option>
      </select>-->

      <div class="filter-search"><span class="active">Library</span> <span class="glyphicon glyphicon-chevron-down"></span>
        <ul id="filter-search-nav">
          <li role="listitem"><a href="#" title="Search all Cornell University Library resources">Library</a></li>
          <li role="listitem"><a href="#" title="Limit your search to cataloged holdings">Library Catalog</a></li>
          <li role="listitem"><a href="#" title="Search libraries worldwide using WorldCat">WorldCat</a></li>
        </ul>
      </div>

      <!--a class="filter" href="#">LAW LIBRARY <span class="caret-icon">></span></a> -->
      <button type="submit" class="submit-search" href="#">
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </div>

    <ul class="external-search">
      <li><a href="https://www.library.cornell.edu/myacct">My Library Account</a> / </li>
      <li><a href="http://newcatalog.library.cornell.edu/databases/subject/Human%20Resources,%20Labor%20&%20Employment">Databases</a> / </li>
      <li><a href="http://guides.library.cornell.edu/prf.php?account_id=9292">Research Guides</a></li>
    </ul>
  </form>
</section>
EOT;

  return $markup;
}

