<?php

/**
 * Implements hook_freedompay_checkout_payload_alter().
 */
function forensics_payments_freedompay_checkout_payload_alter(&$payload, $order, $form_id) {
  if ($form_id == 'forensics_debate_camp_payment') {
    $payload['PurchaseItems'] = _forensics_payments_get_purchase_items();
    $payload['BillingAddress'] = _forensics_payments_get_billing_address();
    $payload['AllowInternationalAddresses'] = TRUE;
  }
}

/**
 * Implements hook_freedompay_transaction_total_alter().
 */
function forensics_payments_freedompay_transaction_total_alter(&$transaction_total, $order, $form_id) {
  if ($form_id == 'forensics_debate_camp_payment') {
    $transaction_total = 0;
    if ($wrapper = _forensics_payments_get_entityform_wrapper()) {
      if (isset($wrapper->field_total_cost)) {
          $transaction_total = $wrapper->field_total_cost->value();
        }
  }
  return $transaction_total;
  }
}

/**
 * Implements hook_freedompay_invoice_prefix().
 */
function forensics_payments_freedompay_invoice_prefix($form_id) {
  if ($form_id == 'forensics_debate_camp_payment') {
    return 'debate';
  }
}

/**
 * Implements hook_form_FORM_ID_alter
 * Adds form validation callback for forensics payment forms
 * Sets the default value to the US
 */
function forensics_payments_form_forensics_debate_camp_payment_entityform_edit_form_alter(&$form, &$form_state) {
  $form['field_country_for_forensics'][LANGUAGE_NONE]['#default_value'] = 'USA';
  $form['#validate'][] = '_forensics_payment_form_validate';
}

function _forensics_payment_form_validate(&$form, &$form_state) {
  $wrapper = entity_metadata_wrapper('entityform', $form_state['entityform']);
  if (!_forensics_payments_amount_is_valid($wrapper)) {
    form_set_error('field_total_cost', 'Please enter an amount.');
  }
}

/**
 * Confirm that user entered a valid amount to pay: numeric and greater than 0
 */
function _forensics_payments_amount_is_valid($wrapper) {
  $amnt = $wrapper->field_total_cost->value();
  return is_numeric($amnt) && $amnt > 0;
}

function _forensics_payments_get_billing_address() {
  $wrapper = _forensics_payments_get_entityform_wrapper();
  $country = $wrapper->field_country_for_forensics->value();
  $country_fix = ($country == 'other') ? '' : $country;
  return array(
    "Street1" => $wrapper->field_address_line_1->value(),
    "Street2" => $wrapper->field_address_line_2->value(),
    "City" => $wrapper->field_city->value(),
    "State" => $wrapper->field_state_as_text->value(),
    "PostalCode" => $wrapper->field_zip_code->value(),
    'CountryCode' => $country_fix,
    'Name' => $wrapper->field_first_name->value() . ' ' . $wrapper->field_last_name->value(),
  );
}

/**
 * Wrapper function for freedompay_entityform_wrapper().
 */
function _forensics_payments_get_entityform_wrapper() {
  return freedompay_entityform_wrapper();
}

/**
 * @todo
 * remove this example function once alunni events tickets implements
 */
function _forensics_payments_get_purchase_items() {
  $wrapper = _forensics_payments_get_entityform_wrapper();
  return array(
    array(
      "Price" => $wrapper->field_total_cost->value(),
      "DisplayOrder" => 1,
      "Description" => "Cornell International Debate Camp",
      "Quantity" => 1,
    ),
  );
}
