<?php

/**
 * @file
 * The social_feed_field_facebook module file.
 */

/**
 * Implements hook_social_feed_fields_channel().
 */
function social_feed_field_twitter_social_feed_fields_channel() {
  return array(
    'twitter' => array(
      'name' => t('Twitter'),
      'description' => t('Twitter: Use @username for users, #hashtag for hashtags or standard terms for standard search'),
      'callback' => '_social_feed_field_twitter',
      'file' => drupal_get_path('module', 'social_feed_field_twitter') . '/includes/social_feed_field.twitter.inc',
      'admin' => array(
        'consumer_key' => array(
          '#type' => 'textfield',
          '#title' => t('Consumer key'),
        ),
        'consumer_secret' => array(
          '#type' => 'textfield',
          '#title' => t('Consumer secret'),
        ),
        'consumer_oauth_token' => array(
          '#type' => 'textfield',
          '#title' => t('Oauth token'),
        ),
        'consumer_oauth_token_secret' => array(
          '#type' => 'textfield',
          '#title' => t('Oauth token secret'),
        ),
        'cache_lifetime' => array(
          '#type' => 'textfield',
          '#title' => t('Cache lifetime'),
          '#description' => t('Cache lifetime in seconds'),
          '#default_value' => SOCIAL_FEED_FIELD_CACHE_LIFETIME,
        ),
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function social_feed_field_twitter_theme($existing, $type, $theme, $path) {
  $theme = array(
    'social_feed_field_twitter_item' => array(
      'variables' => array('message' => NULL, 'field_instance' => array()),
      'template' => 'templates/social-feed-field-twitter-item',
      'file' => 'social_feed_field_twitter.theme.inc',
    ),
  );

  return $theme;
}
