<?php

/**
 * @file
 * The social_feed_field_facebook module file.
 */

/**
 * Implements hook_social_feed_fields_channel().
 */
function social_feed_field_instagram_social_feed_fields_channel() {
  return array(
    'instagram' => array(
      'name' => t('Instagram'),
      'description' => t('Instagram: Only input instagram usernames. Other searches are not possible in the API'),
      'callback' => '_social_feed_field_instagram',
      'file' => drupal_get_path('module', 'social_feed_field_instagram') . '/includes/social_feed_field.instagram.inc',
      'admin' => array(
        'client_id' => array(
          '#type' => 'textfield',
          '#title' => t('Client ID'),
        ),
        'cache_lifetime' => array(
          '#type' => 'textfield',
          '#title' => t('Cache lifetime'),
          '#description' => t('Cache lifetime in seconds'),
          '#default_value' => SOCIAL_FEED_FIELD_CACHE_LIFETIME,
        ),
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function social_feed_field_instagram_theme($existing, $type, $theme, $path) {
  $theme = array(
    'social_feed_field_instagram_item' => array(
      'variables' => array('message' => NULL, 'field_instance' => array()),
      'template' => 'templates/social-feed-field-instagram-item',
      'file' => 'social_feed_field_instagram.theme.inc',
    ),
  );

  return $theme;
}
