<?php

/**
 * Removes field_fax from join_the_ics_mailing_list form
 */
function ilr_forms_public_update_7001() {
  if ($instance = field_info_instance('entityform', 'field_fax', 'join_the_ics_mailing_list')) {
    field_delete_instance($instance);
  }
}

/**
 * Delete field_hcd_topics
 */
function ilr_forms_public_update_7002() {
  field_delete_field('field_hcd_topics');
  field_purge_batch(3);
}
