<?php
/**
 * Implements hook_install().
 */
function tagged_content_block_install() {
  tagged_content_block_update_7001();
}

/**
 * Assigns content types for tagged blocks
 */
function tagged_content_block_update_7001() {
  _tagged_content_block_enable_default_bundles();
}

/**
 * Adds wit, reflections and posts to tagged content block config
 */
function tagged_content_block_update_7002() {
  _tagged_content_block_enable_default_bundles();
}
