<?php
/**
 * @file
 * Code for the Forms feature.
 */

include_once 'forms.features.inc';
include_once 'includes/forms.kerberized.inc';
include_once 'includes/forms.statelists.inc';

require_once DRUPAL_ROOT . '/../config/get_secrets.php';

define('ILRWEB_EMAIL', 'ilrweb@cornell.edu');
define('ILRWEB_BCC_EMAIL', 'ilrwebemailcc@cornell.edu');

/**
 * Implements hook_entityform_presave.
 * Saves the registration date for registration forms
 */
function forms_entityform_presave($entityform) {
  if (_forms_is_event_registration_form($entityform) && $entityform->is_new) {
    _forms_save_registration_date($entityform);
  }
}

/**
 * Implements hook_entity_insert().
 */
function forms_entityform_insert($entityform) {
  if (!$entityform->draft) {
    _forms_process_entityform($entityform);
  }
}

/**
 * Processing function that can be called independently
 * from forms_entityform_insert()
 * @see _elavon_process_entityform() as an example
 */
function _forms_process_entityform($entityform) {
  $processingFunction = '_process_' . $entityform->type;
  if (function_exists($processingFunction)) {
    $processingFunction($entityform);
  }
  else {
    _forms_process_default($entityform);
  }
}

/**
* Implements hook_admin_menu_output_build().
* Adds the entityform submissions page to the admin menu
*/
function forms_admin_menu_output_build(&$content) {
  if (isset($content['menu']) && user_access('view any entityform')) {
    $content['menu']['admin/content']['admin/content/entityform-submissions'] = array(
      '#title' => t('Entityform Submissions'),
      '#href' => 'admin/reports/entityforms',
      '#weight' => 0,
    );
  }
}

/**
 * Implements hook_admin_paths().
 * Sets the entityform submissions pages to the admin theme
 */
function forms_admin_paths() {
  $paths = array(
    'entityform-submissions/submissions/*' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter.
 */
function forms_form_entityform_edit_form_alter(&$form, &$entityform_state, $form_id) {
  // Fill in default values of kerberized forms
  if (_forms_form_is_kerberized($form['#bundle'])) {
    _forms_handle_kerberized_form($form);
  }

  // Hide hidden fields, i.e. any field where the machine name starts with "field_h_"
  foreach ($form as $key=>$value) {
    if (substr($key,0,8) == 'field_h_') {
      $form[$key]['#access'] = FALSE;
    }
  }

  // For Collective Bargaining videos form, redirect if cookie "cbvideoinfo" is set.
  if ($form_id == 'collective_bargaining_videos_entityform_edit_form') {
    if (isset($_COOKIE['Drupal_visitor_cbvideoinfo'])) {
      _forms_collective_bargaining_videos_redirect();
    }
  }
}

/**
 * Collective Bargaining videos redirect
 * The URL to redirect to will get set in the db via drush using the variable "cb_videos_url"
 * What's in the code is a default.
 */
function _forms_collective_bargaining_videos_redirect() {
  $cb_videos_redirect = variable_get('cb_videos_url', 'http://www.ilr.cornell.edu/workerinstitute');
  drupal_goto($cb_videos_redirect);
}

/**
 * Implements hook_form_FORM_ID_alter.
 *   Allows specifying the admin for the form
 *   Adds checkbox to specify NetID login requirement
 */
function forms_form_entityform_type_form_alter(&$form, &$form_state, $form_id) {
  _forms_add_data_attribute_checkbox($form,'send_confirmation_email_to_user');
  _forms_add_data_attribute_checkbox($form,'send_confirmation_email_to_admin');
  _forms_add_data_attribute_checkbox($form,'add_user_name_to_subject_line', 'Append user\'s name to subject line of admin email; some ILR staff appreciate having this; some do not');
  _forms_add_data_attribute_checkbox($form, 'kerberized', 'This form requires NetID authentication');
  _forms_add_data_attribute_checkbox($form, 'add_payment_processing', 'This form is used to process payments');
  _forms_add_admin_email_field($form);
}

/**
 * Add a checkbox for a data attribute to the form
 */
function _forms_add_data_attribute_checkbox(&$form, $key, $description=NULL) {
  if (!$description) {
    $description = ucfirst(str_replace('_', ' ', $key));
  }

  $default = (isset($form['#entityform_type']->data[$key]))
    ? $form['#entityform_type']->data[$key]
    : 0;

  $form['data'][$key] = array(
    '#type' => 'checkbox',
    '#title' => t($description),
    '#weight' => 0,
    '#default_value' => $default,
  );
}

/**
 * Add admin email field to the "edit" form for this entityform
 */
function _forms_add_admin_email_field(&$form) {
  $previously_set_recip = (isset($form['#entityform_type']->data['form_submission_ilr_recipient']))
    ? $form['#entityform_type']->data['form_submission_ilr_recipient']
    : '';
  $form['data']['form_submission_ilr_recipient'] = array(
    '#type' => 'textfield',
    '#title' => t('ILR Admin email'),
    '#weight' => 0,
    '#default_value' => $previously_set_recip,
    '#description' => t('The email address - usually a special mailbox - to send the admin email to when a form is submitted. Also used as From email for user confirmation, so don\'t leave it blank.'),
  );
}

/**
 * Implements hook_theme()
 */
function forms_theme() {
  // Add email templates, based on the tpl.php files in the /templates directory
  $template_array = _forms_get_theme_array_from_template_files();
  return $template_array;
}

/**
 * Generates an array of email templates from files in /templates for forms_theme
 */
function _forms_get_theme_array_from_template_files() {
  $email_template_files_path = drupal_get_path('module', 'forms') . '/templates';
  $template_files = scandir($email_template_files_path);

  // Loop through all the files, add template array elements for the tpl.php files
  foreach ($template_files as $filename) {
    // Check if the filename ends with ".tpl.php"
    if ($template_name = strstr($filename, '.tpl.php', TRUE)) {
      $template_as_key = str_replace('-', '_', $template_name);
      $template_array[$template_as_key] = array(
        'path' => $email_template_files_path,
        'template' => $template_name,
      );
    }
  }
  return $template_array;
}

/**
 * Generates the appropriate email template for entityforms
 * Note that the email template contains underscores, but the actual filename contains hyphens.
 */
function _forms_get_tplphp_file($entityform) {
  $tplphp_file = str_replace('_', '-', $entityform->type);
  $tplphp_file_full_path = drupal_get_path('module', 'forms') . '/templates/' . $tplphp_file . '.tpl.php';

  if (file_exists($tplphp_file_full_path)) {
    return $entityform->type;
  }
  elseif (_forms_is_event_registration_form($entityform)) {
    return 'default_registration_confirmation';
  }
  return 'default_mail';
}

/**
 * Default processing for forms
 */
function _forms_process_default(&$entityform) {
  $admin_email = _forms_get_admin_email($entityform);
  _forms_send_emails($entityform, $admin_email);
}

/**
 * Process Collective Bargaining Videos tracking - set cookie, then do normal processing, then
 * redirect to the list of videos.
 */
function _process_collective_bargaining_videos(&$entityform) {
  user_cookie_save(array ('cbvideoinfo' => 'yes'));
  _forms_process_default($entityform);
  _forms_collective_bargaining_videos_redirect();
}

/**
 * Process WIT email list subscribe / unsubscribe: one email to lyris, one to the user
 */
function _process_wit_email_list_subscribe(&$entityform) {
  $from = 'catherwoodWIT@cornell.edu';
  $email_list = 'wit-l';
  _forms_send_lyris_email($entityform, $from, $email_list);

  $admin_email = _forms_get_admin_email($entityform);
  _forms_send_emails($entityform, $admin_email);
}

function _process_alumni_eNews_subscribe(&$entityform) {
  $from = 'jlw85@cornell.edu';
  $email_list = 'ilr_alumni-l';
  _forms_send_lyris_email($entityform, $from, $email_list);
}

function _forms_send_lyris_email(&$entityform, $from, $email_list) {
  global $ILR_SECRETS;
  $pw = $ILR_SECRETS[$email_list];
  $user_name = _forms_construct_user_name($entityform);
  $entityform_wrapper = _forms_entityform_wrapper($entityform);
  $user_email = $entityform_wrapper->field_email->value();

  $action = $entityform->field_subscribe_or_unsubscribe['und'][0]['value'];
  $email_template = ($action == 'add') ? 'lyris_subscribe' : 'lyris_unsubscribe';
  $subject_lyris = ($action == 'add') ? 's u b s c r i b e  ' : 'u n s u b s c r i b e  ';
  $subject_lyris .= 'via webpage: list ' . $email_list . ', user ' . $user_name;

  $body = theme($email_template, array(
      'list_password'         => $pw,
      'list_name'             => $email_list,
      'user_email'            => $user_email,
      'user_name'             => $user_name,
    ));

  $to = 'lyris@cornell.edu';
  _send_email_for_entity_form($to, $from, $subject_lyris, $body);
}

/**
 * Process Web Services request form
 * sends to remedy and to selected Web Team staff who want to see an email
 */
function _process_web_services_request_form(&$entityform) {
  // Email to remedy
  // Construct subject line with first word of request option, subject user specified, and user's name
  $request_words = str_word_count($entityform->field_web_request_options['und'][0]['value'], 1);
  $short_request_option = trim($request_words[0]);
  $user_name = _forms_construct_user_name($entityform);
  $subject_remedy =
    $short_request_option . ' - ' .
    trim($entityform->field_subject_line['und'][0]['value']) . ' - ' . $user_name;
  $remedy_email = 'ilrwebrequest@cornell.edu';
  _forms_send_remedy_email($entityform, $remedy_email, $subject_remedy);

  // Email to people in the Web group who want an email each time the form is submitted
  $recipients = 'cgh2@cornell.edu, tls245@cornell.edu, fjp2@cornell.edu';
  $subject_web = 'Webreq - ' . $subject_remedy;
  _forms_send_emails($entityform, $recipients, $subject_web);
}


/**
 * Process Tech Services Desktop Support form
 */
function _process_desktop_support_request(&$entityform) {
  $subject = trim($entityform->field_subject_line['und'][0]['value']);
  _forms_process_standard_tech_services_requests($entityform, $subject);
}

/**
 * Process Tech Services Classroom Technologies request form
 */
function _process_classroom_technologies_request(&$entityform) {
  $subject = trim($entityform->field_course_number['und'][0]['value']) . ' - Classroom Tech Req';
  _forms_process_standard_tech_services_requests($entityform, $subject);
}

/**
 * Standard processing for Tech Services forms to send to Remedy
 */
function _forms_process_standard_tech_services_requests(&$entityform, $subject) {
  // This sends to Remedy ticket system, but not to admin at ILR or to user.
  $remedy_email = 'ilrtsrequests@cornell.edu';
  _forms_send_remedy_email($entityform, $remedy_email, $subject);
}


/**
 * Send email to Remedy
 */
function _forms_send_remedy_email(&$entityform, $remedy_email, $subject='Email to remedy') {
  $form_title = _forms_get_form_title($entityform);
  $user_name = _forms_construct_user_name($entityform);
  $user_email = $entityform_wrapper->field_email->value();
  $email_template = 'remedy_email';

  $body = theme($email_template, array(
    'form_title'  => $form_title,
    'form_data'   => _entity_display_form_data($entityform),
  ));

  $to = $remedy_email;
  $from = $user_email;
  _send_email_for_entity_form($to, $from, $subject, $body);
}



/**
 * Process Library contact form
 */
function _process_library_contact_form(&$entityform) {
  $admin_email = trim($entityform->field_library_how_to_direct['und']['value']) . '@cornell.edu';
  _forms_send_emails($entityform, $admin_email);
}

function _forms_library_contact_options() {
  return array(
    'ilrlib' => 'General Information',
    'ilrcirc' => 'Circulation',
    'kheel_center' => 'Kheel Center',
    'ilrref' => 'Research',
  );
}

/**
 * Process Career Services contact form
 */
function _process_career_services_contact_form(&$entityform) {
  // The email value has three chars appended to ensure uniqueness, so they
  // need to be stripped off.  See comments in
  // _forms_career_services_contact_options for more info.
  $email_value_stripped = substr(
    trim($entityform->field_career_services_how_to_dir['und'][0]['value']), 0, -3);
  $admin_email = $email_value_stripped . '@cornell.edu';
  $subject = trim($entityform->field_subject_line['und'][0]['value']);
  _forms_send_emails($entityform, $admin_email, $subject);
}

function _forms_career_services_contact_options() {
  // We need duplicate email addresses (keys in this array; values in the radio buttons)
  // in this list, and Drupal doesn't permit that, so I'm getting around it by appending
  // three characters to each in order to make them unique.  Those three chars will later
  // be stripped out.  Any chars can be used, as long as everything is unique.
  return array(
    'ilrcareers-01' => 'Office of Career Services (General Inquiries)',
    'ilrcareerrecruiting-01' => 'ILR On-Campus Recruiting - student inquiries',
    'djc5-01' => 'ILR On-Campus Recruiting - employer inquiries',
    'djc5-02' => 'ILR Career Fair',
    'mlh15-01' => 'Social Justice Career Fair',
    'jap7-01' => 'CAHRS Executive Roundtable',
    'mlh15-02' => 'Labor Roundtable',
    'mlh15-03' => 'FEX (Freshman Externship Program) / WISP (Winter Internship Program)',
    'ilrab-01' => 'ILR Alumni Bulletin',
    'bk30-01' => 'ILR Credit Internship Program',
    'rmd5-01' => 'Regina M. Duffey Moravek, Director of ILR Career Services',
  );
}

/**
 * Generate options list for year_as_list_text field, based on which form it is
 */
function _year_as_list_text_options($field, $instance = NULL, $entity_type = NULL, $entity = NULL) {
  if ($entity->type == 'labor_roundtable_student_registr') {
    // Class year in the Labor Roundtable registration form starts with current year and goes six years out
    return _forms_year_relative_options(0,6);
  }
  elseif ($entity->type == 'contact_ilr_admissions') {
    // High school grad year for Admissions Contact form starts with 5 years
    // ago and goes to 5 years from now, plus "other".
    $return_array = _forms_year_relative_options(-5,5);
    $return_array[] = 'other';
    return $return_array;
  }
  elseif ($entity->type == 'ilr_information_session_sign_in') {
    // Anticipated entry year at Cornell for Admissions Info Session sign-in form
    // If it's before April: start with current year and go out 6 years
    // April or later: start with the following year and go out 6 years
    return date('n') < 4 ? _forms_year_relative_options(0,6) : _forms_year_relative_options(1,6);
  }
  elseif ($entity->type == 'groat_student_registration') {
    // Expected graduation year in the Groat Student Registration form starts with
    // current year and goes six years out
    return _forms_year_relative_options(0,6);
  }
}

/**
 * Second function to generate options list for years, based on which form it is
 * I need this, because of forms that have more than one field for a set of years
 */
function _forms_year_as_list_text_options2($field, $instance = NULL, $entity_type = NULL, $entity = NULL) {
  if ($entity->type == 'contact_ilr_admissions') {
    // Anticipated entry year at Cornell for Admissions Contact form
    // If it's before April: start with current year and go out 6 years
    // April or later: start with the following year and go out 6 years
    return date('n') < 4 ? _forms_year_relative_options(0,6) : _forms_year_relative_options(1,6);
  }
}


/**
 * Generate a list for a select or radio form element with a list of sequential numbers
 * e.g. absolute years
 */
function _forms_number_absolute_options($first, $last) {
  $num = array();
  if ($first <= $last) {
    for ($num=$first; $num<=$last; $num++) {
      $numList["$num"] = $num;
    }
  }
  else {
    for ($num=$first; $num>=$last; $num--) {
      $numList['$num'] = $num;
    }
  }
  return $numList;
}

/**
 * Generate a list for a select or radio form element with a list of years relative to current year
 * e.g. if $firstOffset = -8 and $lastOffset = 6, this will run from 8 years ago through 6 years from now.
 * If $firstOffset > $lastOffset the years will show up in descending order.
 */
function _forms_year_relative_options($firstOffset, $lastOffset) {
  $currYear = date('Y');
  $first = $currYear + $firstOffset;
  $last = $currYear + $lastOffset;
  return _forms_number_absolute_options($first, $last);
}


/**
 * Generate the options for graduation dates for the graduate student and undergrad
 * Application to Graduate forms.
 * If current date is before Sept. 1st, use current year, otherwise use next year.
 */
function _forms_application_to_graduate_graduation_dates() {
  $grad_year_display = date('Y');
  $today_timestamp = time();

  $switch_date = $grad_year_display . '-09-01';
  $switch_date_timestamp = strtotime($switch_date);

  if ($today_timestamp > $switch_date_timestamp) {
    $grad_year_display++;
  }

  return array(
    'January$grad_year_display' => 'January ' . $grad_year_display,
    'May$grad_year_display' => 'May ' . $grad_year_display,
    'August$grad_year_display' => 'August ' . $grad_year_display,
  );
}

function _forms_full_names_states_and_provinces() {
  $full_names=TRUE;
  $include_other=TRUE;
  $include_states=TRUE;
  $include_provinces=TRUE;
  $include_territories=FALSE;

  return _forms_statelist_options(
    $full_names, $include_other, $include_states, $include_provinces, $include_territories);
}


/**
 * Send user and admin emails
 */
function _forms_send_emails($entityform, $admin_email, $subject='') {
  $sitename = variable_get('site_name', 'Drupal');
  $form_title = _forms_get_form_title($entityform);
  $user_name = _forms_construct_user_name($entityform);
  $email_template = _forms_get_tplphp_file($entityform);
  $entityform_wrapper = _forms_entityform_wrapper($entityform);
  $user_email = $entityform_wrapper->field_email->value();

  // User email
  if (isset($user_email) &&
      _forms_user_receives_confirmation_email($entityform)) {
    $salutation = _form_salutation($user_name);

    $body = theme($email_template, array(
      'salutation'            => $salutation,
      'form_data'             => _entity_display_form_data($entityform),
      'admin_email'           => $admin_email,
      'form_title'            => $form_title,
      'event_info_for_email'  => _forms_get_event_info_for_email($entityform),
      'event_payment_details' => _forms_get_payment_details_for_email($entityform),
      'sitename'              => $sitename,
    ));

    $to = $user_email;
    $from = $admin_email;
    $subject_user = $form_title . ' confirmation';
    _send_email_for_entity_form($to, $from, $subject_user, $body);
  }

  // Admin email
  if (_forms_admin_receives_confirmation_email($entityform)) {
    // Intercept the admin emails when not on prod
    $to = (ilr_is_production_site()) ? $admin_email : ILRWEB_BCC_EMAIL;
    $from = (isset($user_email))
      ? $user_email
      : $admin_email;
    if (empty($subject)) {
      $subject = $form_title . ' submitted';
    }
    if (_forms_admin_subject_line_includes_user_name($entityform)) {
      $subject .= " - $user_name";
    }
    $body =  _entity_display_form_data($entityform);
    _send_email_for_entity_form($to, $from, $subject, $body);
  }
}

/**
 * Get the title of the form
 */
function _forms_get_form_title($entityform) {
  return entity_label('entityform_type', entityform_type_load($entityform->type));
}

/**
 * Get the email address of the form admin, i.e. the person or special mailbox
 * in ILR who needs to get an email when the form is subitted, also this is the
 * "from" address in the confirmation email to the user.
 * If admin recipient isn't supplied in the form, return ILRWEB address
 */
function _forms_get_admin_email($entityform) {
  $entityform_type = entityform_type_load($entityform->type);
  $admin_email = empty($entityform_type->data['form_submission_ilr_recipient'])
        ? ILRWEB_EMAIL : $entityform_type->data['form_submission_ilr_recipient'];
  return $admin_email;
}

/**
 * Checks whether the user name should be appended to the admin subject line
 */
function _forms_admin_subject_line_includes_user_name($entityform) {
  $entityform_type = entityform_type_load($entityform->type);
  $admin_subject_line_includes_user_name = empty($entityform_type->data['add_user_name_to_subject_line'])
    ? FALSE
    : $entityform_type->data['add_user_name_to_subject_line'];
  return $admin_subject_line_includes_user_name;
}

/**
 * Checks whether the USER should receive a confirmation email
 */
function _forms_user_receives_confirmation_email($entityform) {
  $entityform_type = entityform_type_load($entityform->type);
  $user_receives_confirmation_email = empty($entityform_type->data['send_confirmation_email_to_user'])
    ? FALSE
    : $entityform_type->data['send_confirmation_email_to_user'];
  return $user_receives_confirmation_email;
}

/**
 * Checks whether the admin should receive a confirmation email
 */
function _forms_admin_receives_confirmation_email($entityform) {
  $entityform_type = entityform_type_load($entityform->type);
  $admin_receives_confirmation_email = empty($entityform_type->data['send_confirmation_email_to_admin'])
    ? FALSE
    : $entityform_type->data['send_confirmation_email_to_admin'];
  return $admin_receives_confirmation_email;
}

/**
 * Display form data using entityform and entity2text code from Ted Bowman
 */
function _entity_display_form_data($entityform) {
  // Set display of form fields for email and anything else
  $entityform_id = $entityform->entityform_id;
  $entityform = entityform_load($entityform_id);
  $controller = entity_get_controller('entityform');
  $content = $controller->view(array($entityform->entityform_id => $entityform), 'confirmation', NULL, TRUE);
  return drupal_render($content);
}

/**
 * Returns the value of a passed string or a default explicit value if the string is empty
 */
function _get_string_or_default($string, $default='Not specified'){
  return !empty($string) ? $string : $default;
}

/**
 * Formats a non-empty value for a person's name as a salutation
 */
function _form_salutation($name){
  return !empty($name) ? "Dear " . $name . ",\n\n" : "";
}

/**
 * Construct name for salutation, based on form fields (a) full_name or (b) firstname and lastname
 */
function _forms_construct_user_name($entityform){
  $name_for_salutation = '';
  if (array_key_exists('field_full_name', $entityform)) {
    $name_for_salutation = trim($entityform->field_full_name['und'][0]['value']);
  }
  elseif (array_key_exists('field_first_name', $entityform)) {
    $name_for_salutation = trim($entityform->field_first_name['und'][0]['value']);
    if (array_key_exists('field_last_name', $entityform)) {
      $name_for_salutation .= ' ';
      $name_for_salutation .= trim($entityform->field_last_name['und'][0]['value']);
    }
  }
  return $name_for_salutation;
}

/**
 * Set up and send email
 */
function _send_email_for_entity_form($recip, $from, $subject, $body) {
    $params = array(
      'subject' => $subject,
      'content' => $body,
      );

    drupal_mail(
        'forms_std_confirmation',
        'email_confirmation',
        $recip,
        LANGUAGE_NONE,
        $params,
        $from
      );
}

/**
 * Implements hook_mail().
 * This is the email sent to the user
 */
function forms_std_confirmation_mail($key, &$message, $params) {
  $message['headers']['MIME-Version'] = '1.0';
  $message['headers']['Content-Type'] = 'text/plain;charset=utf-8';
  $message['headers']['Bcc'] = ILRWEB_BCC_EMAIL;
  $message['subject'] = $params['subject'];
  $message['body'][] = $params['content'];
}

/**
 * Determines whether the form being saved is a registration form
 * @todo Consider refactoring, since "field_referenced_node" shouldn't probably
 * be the defining characteristic of a registration form
 */
function _forms_is_event_registration_form($entityform) {
  if (isset($entityform->field_referenced_node)) {
    if (module_exists('registration_pages')
        && _registration_pages_is_event_registration_form($entityform)) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Wrapper function for _registration_pages_get_event_markup()
 */
function _forms_get_event_info_for_email($entityform) {
  if (_forms_is_event_registration_form($entityform)) {
    module_load_include('module', 'registration_pages');
    $entityform_wrapper = _forms_entityform_wrapper($entityform);
    $node = $entityform_wrapper->field_referenced_node->value();
    return _registration_pages_get_event_markup($node);
  }
  return '';
}

/**
 * Wrapper function for _elavon_get_payment_details_for_email()
 */
function _forms_get_payment_details_for_email($entityform) {
  $entityform_type = entityform_type_load($entityform->type);
  $has_payment = $entityform_type->data['add_payment_processing'];
  if ($has_payment && module_exists('elavon')) {
    return _elavon_get_payment_details_for_email($entityform);
  }
  return '';
}

/**
 * Saves the date of the event to the hidden field on the entityform
 */
function _forms_save_registration_date($entityform) {
  $entityform_wrapper = _forms_entityform_wrapper($entityform);
  //'default_value_function' => 'entityreference_current_field_default_value',
  $event_date_save = $entityform_wrapper->field_referenced_node->field_event_date->value();
  if (!empty($event_date_save)) {
    $entityform_wrapper->field_h_event_date->set($event_date_save);
  }
}

/**
 * Creates or retrieves an entitymetadata wrapper for the form
 */
function _forms_entityform_wrapper($entityform) {
  $wrapper = &drupal_static(__FUNCTION__);
  if (!isset($wrapper)) {
    $wrapper = entity_metadata_wrapper('entityform', $entityform);
  }
  return $wrapper;
}
