<?php

function _ilr_redirects_load_redirects($filename) {
  $redirects = array();
  $file_path = drupal_get_path('module','ilr_redirects') . '/'.$filename.'.csv';
  ini_set('auto_detect_line_endings', TRUE);
  $file = fopen($file_path, 'r');
  if ($file) {
    while (($redirect = fgetcsv($file)) !== FALSE) {
      $redirects[] = array(
        'source' => strtolower(trim($redirect[0], '/')),
        'destination' => strtolower(trim($redirect[1], '/')),
      );
    }
    fclose($file);
  }

  return $redirects;
}

function _ilr_redirects_create_redirects($filename='ilr-website-redirects', $update_alias = FALSE) {
  if (module_exists('redirect')) {
    $redirects = _ilr_redirects_load_redirects($filename);
    foreach ($redirects as $redirect) {
      if ($update_aliases) {
      $update_db = db_update('url_alias')
        ->fields(array('alias' => $redirect['destination']))
        ->condition('alias', $redirect['source'], '=')
        ->execute();
      }
      $new_redirect = new stdClass();
      redirect_object_prepare($new_redirect);
      $new_redirect->source = $redirect['source'];
      $new_redirect->redirect = $redirect['destination'];
      $new_redirect->language = LANGUAGE_NONE;
      // Check if the redirect exists before saving.
      $hash = redirect_hash($new_redirect);
      if (!redirect_load_by_hash($hash)) {
        redirect_save($new_redirect);
      }
    }
  }
}
