<?php

/**
 * @file entityform_block.module
 * Provides blocks for entity form types.
 *
 * Originally from sandbox project
 * @see https://www.drupal.org/sandbox/joachim/2045865
 * Changed so all Entityform types have blocks.
 */

/**
 * Implements hook_block_info().
 */
function entityform_block_block_info() {
  $blocks = array();
  foreach (entityform_get_types() as $entityform_type) {
    $blocks[$entityform_type->type] = array(
      'info' => t('Entityform: ' . $entityform_type->label()),
      // DRUPAL_CACHE_PER_ROLE will be assumed.
    );
  }

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function entityform_block_block_view($delta = '') {
  module_load_include('inc', 'entityform', 'entityform.admin');

  $block = array();
  $entityform_type = entityform_get_types($delta);
  if (!empty($entityform_type)) {
    $block['subject'] = $entityform_type->label();
    $block['content'] = entityform_form_wrapper(entityform_empty_load($entityform_type->type), 'submit', 'embedded');
  }

  return $block;
}


/**
 * Implements hook_entityform_type_update().
 *
 * Fixes a bug with blockreference where the block doesn't show up
 * See similar issue at https://drupal.org/node/1891928#comment-7093512
 */
function entityform_block_entityform_type_update($entity) {
  block_flush_caches();
}
