<?php
/**
 * @file
 * Code for the People Profiles feature.
 *
 * @todo Currently the View areas_expertise_taxonomy_term is used display terms.
 * because this takes over the path taxonomy/term/% it has to be used for all terms.
 * Currently no term pages are shown but if they are in the future this should be changed.
 * Possible fixes:
 *  1. https://www.drupal.org/project/tvi
 *  2. hook_menu_alter and take over taxonomy/term/%taxonomy_term to check term and embed_view
 */

include_once 'people_profiles.features.inc';

require_once variable_get('config_dir') .  '/ilr_departments.php';

/**
 * Implements hook_init().
 */
function people_profiles_init() {
  global $theme;
  if ($theme == 'ilr_theme') {
    $inview_js = libraries_get_path('inview') . '/jquery.inview.min.js';
    drupal_add_js($inview_js, array('type' => 'file', 'scope' => 'footer'));
  }
}

function people_profiles_form_views_exposed_form_alter(&$form, &$form_state) {
  if ($form['#id'] == 'views-exposed-form-people-profile-teasers-block') {
    $form['field_last_name_value']['#type'] = 'select';
    $form['field_last_name_value']['#size'] = NULL;
    $form['field_last_name_value']['#attributes']['title'] = 'View people whose last name begins with the letter';
    $form['field_last_name_value']['#attributes']['class'][] = 'people-profile-alpha-select';
    $all = array('' => '- All -');
    $alphas = array_combine(range('a','z'), range('A','Z'));
    $form['field_last_name_value']['#options'] = array_merge($all, $alphas);
  }
}

/**
 * Implements hook_user_insert()
 * Looks for a profile with matching netID
 * If found, assigns new user as the owner
 */
function people_profiles_user_insert(&$edit, $account, $category) {
  if($account->is_new) {
    // Check to see if there is a profile page connected to this netID
    if ($profile_page = _people_profiles_find_profile_by_netid($account->name)) {
      $profile_page->uid = $account->uid;
      node_save($profile_page);
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function people_profiles_node_presave($node) {
  if ($node->type == 'people_profile' && !$node->is_new) {
    $wrapper = _people_profiles_node_wrapper($node);
    $title = _people_profiles_set_title($wrapper);
    $wrapper->title->set($title);
  }
}

/**
 * Implements hook_node_view().
 */
function people_profiles_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'people_profile') {
    if ($view_mode == 'teaser') {
      if(!count($node->field_profile_image)) {
        $placeholder = '/' . drupal_get_path('theme', 'ilr_theme') . '/images/directory-default.jpg';
        $node->content['field_profile_image']['#markup'] = '<div class="field field-type-image"><img class="placeholder" src="'.$placeholder.'" alt="ILR School Ives Hall" /></div>';
      }
      unset($node->content['links']['node']['#links']['node-readmore']);
    }
    elseif ($view_mode == 'full') {
      drupal_add_js(drupal_get_path('module', 'people_profiles') . '/people_profiles.js', array(
          'type' => 'file',
          'scope' => 'footer'
        ));
    }
  }
}

function people_profiles_preprocess_page(&$variables) {
  if (!empty($variables['node']) && $variables['node']->type == 'people_profile') {
    ilr_add_section_title($variables, 'People at ILR');
  }
}

function _people_profiles_set_title($wrapper) {
  return $wrapper->field_first_name->value() . ' ' . $wrapper->field_last_name->value();
}

/**
 * Implements hook_preprocess_node
 *   Redirects if not ready to show the full node
 *   Adds additional markup
 *   @todo Fix bug related to new lines not rendering from textareas. @see _ilr_theme_add_line_breaks for further info.
 */
function people_profiles_preprocess_node(&$variables) {
  if($variables['type'] == 'people_profile') {
    $has_fax = !empty($variables['content']['field_fax']);
    if ($has_fax) {
      $variables['content']['field_fax'][0]['#markup'] = '(f) ' . $variables['content']['field_fax'][0]['#markup'];
    }
    if ($variables['view_mode'] == 'full') {
      $wrapper = _people_profiles_node_wrapper($variables['node']);
      if (!$wrapper->field_display_in_faculty_lists->value()) {
        $title = _people_profiles_create_anchor($variables['title']);
        return _people_profiles_redirect_to_people_page($title);
      }
      $type = $wrapper->field_profile_type->value();
      $variables['classes_array'][] = "profile-type-$type";

      // Move title to correct location
      if (isset($variables['content']['field_working_title'])) {
        $title = $wrapper->title->value();
        $markup = "<div class='crumb'> people / $type</div>";
        $markup .= "<h2 class='profile__name heading--strong'>$title</h2>";
        $markup .= $wrapper->field_working_title->value();
        $variables['content']['field_working_title'][0]['#markup'] = $markup;
      }
    }
    elseif ($variables['view_mode'] == 'teaser') {
      if ($variables['field_display_in_faculty_lists'][LANGUAGE_NONE][0]['value'] != 1) {
        // Remove the links to the node
        $variables['remove_title_link'] = TRUE;
        if (count($variables['field_profile_image'])) {
          unset($variables['content']['field_profile_image'][0]['#path']);
        }
      }
      if (count($variables['field_working_title'])) {
        $variables['content']['field_working_title'][0]['#markup'] = _people_profiles_get_primary_title($variables['content']['field_working_title'][0]['#markup']);
      }
      // Remove fax from all pages except full staff view
      if (!_people_profiles_is_full_staff_view()) {
        if ($has_fax) {
          unset($variables['content']['field_fax']);
        }
      }
      $variables['title_attributes_array'] = array(
        'id' => _people_profiles_create_anchor($variables['title']),
      );
    }
  }
}

function people_profiles_views_post_render(&$view, &$output, &$cache) {
  if ($view->name == 'people_profile_teasers') {
    drupal_add_js(drupal_get_path('module', 'people_profiles') . '/people_profiles.js', array(
          'type' => 'file',
          'scope' => 'footer'
        ));
    $last_name_map = _people_profiles_create_last_name_letter_map();
    drupal_add_js(array(
      'people_profiles' => array(
        'lastNameMap' => $last_name_map,
      )), 'setting');
  }

}

function _people_profiles_create_last_name_letter_map() {
  $last_name_map = array();
  $people_nids = _people_profiles_get_profile_nids('all');
  $people_nodes = node_load_multiple($people_nids);
  foreach ($people_nodes as $node) {
    $last_name = $node->field_last_name[LANGUAGE_NONE][0]['safe_value'];
    $first_letter = strtolower(mb_substr($last_name, 0, 1));
    $alias = drupal_get_path_alias('node/' . $node->nid);
    $anchor = str_replace('people/', '#', $alias);
    $last_name_map[$anchor] = $first_letter;
  }
  return json_encode($last_name_map);
}

function _people_profiles_get_primary_title($full_title) {
  if ($pos = strpos($full_title,"\n")) {
    return substr($full_title, 0, $pos);
  }
  return $full_title;
}
/**
 * Implements hook_form_alter
 * Calls the appropriate form alter depending on profile type
 */
function people_profiles_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'people_profile_node_form') {
    // Check to see whether the profile is for faculty
    if (count($form['field_profile_type']['und']['#default_value']) && $form['field_profile_type']['und']['#default_value'][0] == 'faculty') {
      _people_profiles_render_ai_tab_contents($form);
    } // Remove the AI tab and other fields
    else {
      _people_profiles_process_staff_form($form);
    }

    // Remove editing the profile type except for admins
    global $user;
    if (!in_array('administrator', $user->roles)) {
      $form['field_profile_department']['#disabled'] = 1;
      $form['field_phone']['#disabled'] = 1;
      $form['field_local_address']['#disabled'] = 1;
      $form['field_email']['#disabled'] = 1;
      $form['field_address_line_1']['#disabled'] = 1;
      $form['field_faculty_on_leave']['#disabled'] = 1;
      $form['field_profile_type']['#access'] = FALSE;
    }
    $form['title']['#access'] = FALSE; // Use first and last name instead

    // Remove the netid field
    if (isset($form['field_netid'])) {
      $form['field_netid']['#access'] = FALSE;
    }
  }
}

function people_profiles_field_group_build_pre_render_alter(&$element, $group, &$form) {
  if (isset($element['#bundle'])
    && $element['#bundle'] == 'people_profile'
    && $element['#view_mode'] == 'full') {
    $wrapper = _people_profiles_node_wrapper($element['#node']);
    $type = $wrapper->field_profile_type->value();

    // Handle issues with use of the local address field
    _people_profiles_process_address($element);

    if ($type == 'faculty') {
      _people_profiles_process_faculty_view($element);
    } // Handle non-faculty oddities, such as missing image or content
    else {
      if (_prople_profiles_content_area_is_empty($element['group_main_content'])) {
        _people_profiles_move_sidebar_content($element);
      }
      if (!$element['group_profile_highlighted']['field_profile_image']) {
        _people_profiles_handle_missing_image($element);
      }
    }
  }
}

function _prople_profiles_content_area_is_empty($main_content_array) {
  foreach ($main_content_array as $key => $value) {
    if (strpos($key, 'field') === 0) {
      $content = $value;
    }
    if ($content) {
      return FALSE;
    }
  }
  return TRUE;
}

function _people_profiles_move_sidebar_content(&$element) {
  $element['group_profile_highlighted']['group_title_and_focus']['moved_sidebar_content'] = $element['group_profile_sidebar'];
  $element['group_profile_highlighted']['group_title_and_focus']['moved_sidebar_content']['#prefix'] = '<div class="moved-sidebar">';
  unset($element['group_profile_sidebar']);
}

function _people_profiles_handle_missing_image(&$element) {
  // Add some padding if missing an image
  $prefix = $element['group_profile_highlighted']['#prefix'];
  $new_prefix = implode(' no-image', str_split($prefix, strlen($prefix) - 2));
  $element['group_profile_highlighted']['#prefix'] = $new_prefix;
}

/**
* Implements hook_block_info().
*/
function people_profiles_block_info($delta = '') {
  $blocks = array(
    'faculty_landing_page' => array(
      'info' => "Faculty Landing Page",
    ),
    'people_landing_page' => array(
      'info' => "People Landing Page",
    ),
  );

  $departments = _people_profiles_get_faculty_departments();
  foreach ($departments as $key => $value) {
    $blocks[$key] = array(
      'info' => "Faculty for {$value}",
    );
  }
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function people_profiles_block_view($delta = '') {
  if (strpos($delta, 'landing_page') !== FALSE) {
    $block = array(
      'subject' => '',
      'content' => _people_profiles_people_landing_page($delta),
    );
  }
  else {
    $block = array(
      'subject' => 'Faculty',
      'content' => _people_profiles_department_faculty_view($delta),
    );
  }
  drupal_add_js(drupal_get_path('module', 'people_profiles') . '/people_profiles.js', array(
          'type' => 'file',
          'scope' => 'footer'
        ));
  return $block;
}

function _people_profiles_people_landing_page($delta) {
  if ($delta == 'faculty_landing_page') {
    $markup = _people_profiles_faculty_people_view();
  } else {
    $markup = _people_profiles_all_people_view();
  }
  $block['content'] = array(
    '#markup' => $markup,
  );

  return $block;
}

function _people_profiles_faculty_people_view() {
  $faculty_nids = _people_profiles_get_profile_nids('faculty');
  return _people_profiles_load_people_view_by_nids($faculty_nids);
}

function _people_profiles_all_people_view() {
  $people_nids = _people_profiles_get_profile_nids('all');
  return _people_profiles_load_people_view_by_nids($people_nids);
}

function _people_profiles_load_people_view_by_nids($nids) {
  $people_nodes = node_load_multiple($nids);
  $node_view = node_view_multiple($people_nodes, $view_mode = 'teaser');
  return drupal_render($node_view);
}

/**
* Custom function to query for the faculty members
*/
function _people_profiles_department_faculty_view($delta) {
  $profile_nid_array = _people_profiles_get_profile_nids($delta);
  if (count($profile_nid_array) > 0) {
    $markup = "<ul class='department-faculty'>\n";
    foreach ($profile_nid_array as $key => $nid) {
      $profile = node_load($nid);
      $link = drupal_get_path_alias("node/$nid");
      $markup .= "<li><a href='/{$link}'>{$profile->title}</a></li>\n";
    }
    $markup .= "</ul>\n";

    $block['content'] = array(
      '#markup' => $markup,
    );
  }
  else {
    // There are no faculty members, so don't render the block
    $block = array();
  }

  return $block;
}

function _people_profiles_get_profile_nids($type='all'){
  $nodes_info = array();
  $query = new EntityFieldQuery();

  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'people_profile')
    ->propertyCondition('status', 1)
    ->fieldOrderBy('field_last_name', 'value', 'ASC');

  if ($type != 'all') {
    $query->fieldCondition('field_profile_type', 'value', 'faculty');
    if ($type != 'faculty') {
      $department_key = $type;
      $query->fieldCondition('field_profile_department', 'value', $department_key);
    }
  }

  $result = $query->execute();

  if (!empty($result)) {
    $nids = array_keys($result['node']);
    return $nids;
  }
  return NULL;
}

/**
 * Prepare the title to become a usable named anchor
 * - remove encoded single quotes
 * - call drupal_clean_css_identifier()
 */
function _people_profiles_create_anchor($title) {
  return strtolower(drupal_clean_css_identifier(str_replace("&#039;","",$title)));
}
/**
 * Sets up the redirect to the people landing page
 * Anchors added in
 */
function _people_profiles_redirect_to_people_page($title) {
  drupal_goto('people', array('fragment' => $title));
}
/**
 * Handles rendering the output of Activity insight fields
 * and whether to add a link to the person (poorly named 'field_display_in_faculty_lists')
 */
function _people_profiles_render_ai_tab_contents(&$form) {
  // Remove the option to use non-AI data except for admins
  global $user;
  if (!in_array('administrator', $user->roles)) {
    $form['field_display_in_faculty_lists']['#access'] = false;
  }

  $form['field_visibility_settings'][LANGUAGE_NONE]['#title'] = 'The following information is drawn directly from Activity Insight. (Check those sections you would like to <em>exclude</em> from public display)';

  foreach ($form as $field_name => $value) {
    if (strpos($field_name, 'field_ai') === 0 || $field_name == 'field_areas_of_expertise') {
      $content = _people_profiles_get_default_value($form[$field_name]);
      $field_hint = _people_profiles_get_description_as_help_text($form[$field_name]);

      if (array_key_exists($field_name, $form['field_visibility_settings'][LANGUAGE_NONE]['#options'])) {
        $option_text = $form['field_visibility_settings'][LANGUAGE_NONE]['#options'][$field_name];
        $form['field_visibility_settings'][LANGUAGE_NONE]['#options'][$field_name] = '<strong>' . $option_text .'</strong> '. $field_hint . ' <blockquote>' . $content . '</blockquote>';
        $form[$field_name]['#access'] = false;
      }
    }
  }
}

/**
 * Handles dumb logic for finding the default value of a field
 */
function _people_profiles_get_default_value($field) {
  $default_value = '';
  // "Filtered text" text processing
  if (isset($field[LANGUAGE_NONE][0]['#default_value'])) {
    $default_value = $field[LANGUAGE_NONE][0]['#default_value'];
  } // "Plain text" text processing
  elseif (isset($field[LANGUAGE_NONE][0]['value']['#default_value'])) {
    $default_value = $field[LANGUAGE_NONE][0]['value']['#default_value'];
  } // Taxonomy terms
  elseif (isset($field[LANGUAGE_NONE]['#default_value'])) {
    $default_value = $field[LANGUAGE_NONE]['#default_value'];
  }

  return $default_value;
}

/**
 * Handles dumb logic for creating the help text of a field
 */
function _people_profiles_get_description_as_help_text($field) {
  return  (isset($field[LANGUAGE_NONE][0]['#description']) && ! empty($field[LANGUAGE_NONE][0]['#description'])) ?
    ' <span class="field-note">('.$field[LANGUAGE_NONE][0]['#description'].')</span>' : '';
}

/**
 * Custom function to process faculty profiles
 * by handling the optional AI elements
 * and adding the sidebar thumb
 */
function _people_profiles_process_faculty_view(&$element) {
  _people_profiles_process_optional_ai_elements($element);
  // _people_profiles_add_sidebar_thumb($element);
  _people_profiles_update_vita_link($element);
}

function _people_profiles_add_sidebar_thumb(&$element) {
  if (isset($element['field_profile_image'])) {
    $thumb = $element['field_profile_image'];
    $thumb[0]['#image_style'] = 'focussed_thumbnail';
    $element['field_generated_thumb'] = $thumb;
    $element['group_profile_sidebar']['field_generated_thumb'] = $thumb;
    $element['group_profile_sidebar']['field_generated_thumb'];
    $element['#group_children']['field_generated_thumb'] = 'group_profile_sidebar';
  }
}

/**
 * Check for a vita file
 * If present, show the description text or default text
 */
function _people_profiles_update_vita_link(&$element) {
  if (isset($element['field_ilrweb_vita_file'][0])) {
    if (!isset($element['field_ilrweb_vita_file'][0]['#file']->description)) {
      $element['field_ilrweb_vita_file'][0]['#file']->description = 'Download';
    }
  }
}

/**
 * Hides faculty-only fields
 */
function _people_profiles_process_staff_form(&$form) {
  $form['field_ilrweb_vita_file']['#access'] = 0;
  $form['field_faculty_on_leave']['#access'] = 0;
  $form['field_office_hours']['#access'] = 0;
  // Hide the AI fieldgroup
  field_group_hide_field_groups($form, array('group_activity_insight'));
}

/**
 * Custom function to remove the local address if there is a campus address
 * Many people erringly put a local address when they shouldn't
 * But all people without a campus address use the local address
 */
function _people_profiles_process_address(&$element) {
  if(count($element['group_profile_sidebar']['group_contact_info']['field_address_line_1']) > 0) {
    unset($element['group_profile_sidebar']['group_contact_info']['field_local_address']);
  }
}

/**
 * Custom function to return optional fields populated from AI
 * Add any AI fields here that faculty can choose to toggle on/off
 * Naming conventions map array keys to field machine name
 * Also see allowed_values_function in people_profiles.features.field_base.inc
 */
function _people_profiles_activity_insight_options_list() {
  return array(
    'field_ai_overview' => 'Overview',
    //'field_ai_outreach_activities' => '',
    'field_ai_teaching_statement' => 'Teaching Statement',
    'field_ai_research_statement' => 'Research Statement',
    'field_ai_service_statement' => 'Service Statement',
    'field_ai_outreach_statement' => 'Outreach Statement',
    'field_ai_publications' => 'Publications',
    'field_ai_professional_activities' => 'Professional Activities',
    'field_ai_honors_awards' => 'Honors and Awards',
    'field_areas_of_expertise' => 'Areas of Expertise',
    'field_ai_other_expertise' => 'Other Areas of Expertise',
    'field_ai_links' => 'Links',
  );
}

/**
 * Loops through people profile elements and checks visiblity settings
 * See _people_profiles_activity_insight_options_list for the values that are
 * output as checkboxes that can be excluded
 */
function _people_profiles_process_optional_ai_elements(&$element) {
  $wrapper = _people_profiles_node_wrapper();
  $excluded_fields = $wrapper->field_visibility_settings->value();
  foreach ($excluded_fields as $key => $field_name) {
    if (isset($element['group_main_content'][$field_name])) {
      unset($element['group_main_content'][$field_name]);
    }
    else if (isset($element['group_profile_sidebar'][$field_name])) {
      unset($element['group_profile_sidebar'][$field_name]);
    }
  }
}

/**
 * Searches for a profile with a corresponding NetID
 * @param  String $netId The NetID supplied by the saml login
 * @return Node        The node with the supplied NetID
 */
function _people_profiles_find_profile_by_netid($netId) {
  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'people_profile')
    ->fieldCondition('field_netid','value',$netId)
    ->execute();
  if (count($entities) == 1) {
    return node_load(key($entities['node']));
  }
  return FALSE;
}

function _people_profiles_get_department_select_options() {
  $department_list = _people_profiles_get_department_list();
  $departments = array();
  foreach ($department_list as $name) {
    $key = _people_profiles_sanitize_department_key($name);
    $departments[$key] = $name;
  }

  return $departments;
}

function _people_profiles_get_department_list() {
  global $ILR_DEPARTMENTS;
  $departments = array();
  foreach ($ILR_DEPARTMENTS as $key => $name) {
    $departments[] = _people_profiles_sanitize_department_name($name);
  }
  return $departments;
}

function _people_profiles_get_faculty_departments() {
  $department_names = array(
    "Economics",
    "Human Resource Studies",
    "International and Comparative Labor",
    "Labor Relations, Law, and History",
    "Organizational Behavior",
    "Social Statistics",
  );

  $departments = array();

  foreach ($department_names as $name) {
    $key = _people_profiles_sanitize_department_key($name);
    $departments[$key] = $name;
  }

  return $departments;
}

function _people_profiles_node_wrapper($node=NULL) {
  $wrapper = &drupal_static(__FUNCTION__);
  if (!isset($wrapper)) {
    $wrapper = entity_metadata_wrapper('node', $node);
  }
  return $wrapper;
}

function _people_profiles_sanitize_department_name($name) {
  $strings_to_remove = array('-ILR','Ext-','ILR -','LIBR -');
  $name = str_replace($strings_to_remove, '', $name);
  $name = trim($name);
  return $name;
}

function _people_profiles_sanitize_department_key($name) {
  $name = _people_profiles_sanitize_department_name($name);
  $key = strtolower($name);
  $key = preg_replace('@[^a-z0-9_]+@','_',$key);
  if (strlen($key) > 30) {
    $key = substr($key, 0, 30);
  }
  return $key;
}

function _people_profiles_is_full_staff_view() {
  $current_nid = &drupal_static(__FUNCTION__);
  if (!isset($current_nid)) {
    if ($node = menu_get_object()) {
      $current_nid = $node->nid;
    }
  }
  return $current_nid == 249071;
}
