<?php
/**
 * @file
 * Code for the People Profiles feature.
 */

include_once 'people_profiles.features.inc';

/**
 * Implements hook_preprocess_node
 *   Checks to see whether the Use AI flag has been set
 *   Removes appropriate columns based on the flag
 */
function people_profiles_preprocess_node(&$variables) {
  if($variables['type'] == 'people_profile' && $variables['field_profile_type'][0]['value'] == 'faculty') {
    _people_profiles_process_faculty_view($variables);
  }
}

/**
 * Custom function to process faculty profiles
 * by hiding either the ilrweb or activity insight fields
 * This only gets called if the profile is a faculty
 */
function _people_profiles_process_faculty_view(&$variables) {
  // This assumes a common naming convention for irlweb and ai fields,
  // which get set during the initial field creation process in the UI
  $use_activity_insight = $variables['field_use_ai_data'][0]['value'];
  $field_name_prefix =
    ($use_activity_insight)
      ? 'field_ilrweb'
      : 'field_ai';
  if ($use_activity_insight) { // Deal with optional fields
    _people_profiles_process_optional_ai_elements($variables);
  }
  _people_profiles_hide_fields_with_prefix($variables, $field_name_prefix);
}

function _people_profiles_hide_fields_with_prefix(&$variables, $prefix) {
  foreach ($variables as $key => $value) { // $key is the field name
    if (strpos($key, $prefix) === 0) {
      unset($variables['content'][$key]);
    }
  }
}

/**
 * Custom function to return optional fields populated from AI
 * Add any AI fields here that faculty can choose to toggle on/off
 * Naming conventions map array keys to field machine name
 * Also see allowed_values_function in people_profiles.features.field_base.inc
 */
function _people_profiles_activity_insight_options_list() {
  return array(
    'field_ai_overview' => 'Overiew',
    //'field_ai_outreach_activities' => '',
    'field_ai_professional_activities' => 'Professional Activities',
    'field_ai_honors_awards' => 'Honors and Awards',
    'field_ai_publications' => 'Publications',
  );
}

/**
 * Loops through people profile elements and checks visiblity settings
 * See _people_profiles_activity_insight_options_list for the values that are
 * output as checkboxes that can be enabled
 */
function _people_profiles_process_optional_ai_elements(&$variables) {
  $enabled_fields = _people_profiles_get_visible_ai_fields($variables['field_visibility_settings']);

  $optional_fields = array_keys(_people_profiles_activity_insight_options_list());
  foreach ($variables as $field_name => $value) {
    if (in_array($field_name, $optional_fields)) {
      if (!in_array($field_name, $enabled_fields)) {
        unset($variables['content'][$field_name]);
      }
    }
  }
}

/**
 * Determines which checkboxes have been selected from the field_visibility_settings
 * @param  Array $field_visibility_settings
 * @return Array A single dimensional array with the fieldnames as string values
 */
function _people_profiles_get_visible_ai_fields($field_visibility_settings) {
  $enabled_fields = array();
  foreach ($field_visibility_settings as $key => $value) {
    $enabled_fields[] = $value['value'];
  }
  return $enabled_fields;
}
