https://www.{default}/:
  type: upstream
  upstream: app:http
  cache:
    enabled: true
    cookies: ['/^SS?ESS/', '/^SimpleSAML/', 'cuwltgttime']
  redirects:
    expires: 300s
    paths:
      '^/trianglefire/?(.*)':
        to: 'http://trianglefire.ilr.cornell.edu/$1'
        regexp: true
      '^/ilgwu/?(.*)':
        to: 'http://ilgwu.ilr.cornell.edu/$1'
        regexp: true
      '^/edi/?(.*)':
        to: 'http://www.yti.cornell.edu/$1'
        regexp: true
      '^/library/kheel-center(.*)':
        to: 'https://catherwood.library.cornell.edu/kheel'
        regexp: true

https://{default}/:
  type: redirect
  to: https://www.{default}/
