# 2023-08: The internal `d7` subdomain was somehow crawled by google. So it is
# now a redirect to `www` and a new `d7-edit` subdomain has been added.
# {default} has been changed to `d7-edit`.
"https://d7.ilr.cornell.edu/":
  type: redirect
  to: https://www.ilr.cornell.edu/
"https://{default}/":
  type: upstream
  upstream: app:http
  cache:
    enabled: true
    cookies: ['*']
  redirects:
    expires: 300s
    paths:
      '^/trianglefire/?(.*)':
        to: 'http://trianglefire.ilr.cornell.edu/$1'
        regexp: true
      '^/ilgwu/?(.*)':
        to: 'http://ilgwu.ilr.cornell.edu/$1'
        regexp: true
      '^/edi/?(.*)':
        to: 'http://www.yti.cornell.edu/$1'
        regexp: true
      '^/library/kheel-center(.*)':
        to: 'https://catherwood.library.cornell.edu/kheel'
        regexp: true
      '/student-experience':
        to: 'https://www.ilr.cornell.edu/current-students'
        code: 301
      '/programs/professional-programs':
        to: 'https://www.ilr.cornell.edu/programs/professional-education'
        code: 301
      '/about-ilr/faculty-and-staff-resources':
        to: '/faculty-and-staff-resources'
        code: 301
      '/programs/academics':
        to: '/academics'
        code: 301
      '/faculty-and-staff-resources/technology-services':
        to: 'https://tdx.cornell.edu/TDClient/82/Portal/Home/'
        code: 301
"https://archive.{default}/":
  type: upstream
  upstream: app:http
  cache:
    enabled: false
