<?php
/**
 * @file
 * Code for the Promo feature.
 */

include_once 'promo.features.inc';

function promo_preprocess_node(&$variables) {
  if ($variables['type'] == 'promo' && drupal_is_front_page()) {
    if (!empty($target = $variables['field_internal_link'])) {
      $target = $variables['field_internal_link'][LANGUAGE_NONE][0]['target_id'];
      $alias = drupal_get_path_alias('node/' . $target);
      $variables['content']['cta'] = [
        '#markup' => '<div class="link link__cta"><a class="button" href="'. $alias .'">Learn More</a></div>',
      ];
    }
  }
}

