<?php
/**
 * @file
 * Code for the registration-pages feature.
 */

include_once 'registration_pages.features.inc';

/**
 * Implements hook_preprocess_hook()
 */
function registration_pages_preprocess_node(&$variables) {
  if ($variables['type'] == 'registration_page'){
    $variables['content']['event_info']['#markup'] =
      _registration_pages_get_event_markup($variables['node']);
    $variables['content']['event_info']['#weight'] = 1;

    // Confirm that the form registration dates are valid
    if (!empty($variables['node']->field_event_registration_period)) {
      _registration_pages_process_registration_period($variables);
    }

    // Set the weight on the form
    $variables['content']['field_registration_form']['#weight'] = 2;
  }
}

/**
 * Implements hook_token_info().
 */
function registration_pages_token_info() {
  $tokens['event_info'] = array(
    'name' => t('Event Info'),
    'description' => t('Includes date, time, location'),
  );

  $return_array = array(
    'tokens' => array('entityform' => $tokens),
  );
  return $return_array;
}

/**
 * Implements hook_tokens().
 */
function registration_pages_tokens($type, $tokens, array $data = array(), array $options = array()) {

  $return = array();

  if ($type == 'entityform' && !empty($data['entityform'])) {
    $entityform = $data['entityform'];

    // Check that event_info exists - if so we need to assign to it
    if (isset($tokens['event_info'])) {
      if (_registrations_pages_is_reg_form($entityform)) {
        $entityform_wrapper = entity_metadata_wrapper('entityform', $entityform);
        $node = $entityform_wrapper->field_referenced_node->value();
        $return[$tokens['event_info']] = _registration_pages_get_event_markup($node);
      }
    }
  }

  return $return;
}

/**
 * Check if a form is a registration form, i.e. if page type is registration_page
 */
function _registrations_pages_is_reg_form($entityform) {
  // Wrap entityform in an entity metadata wrapper - makes it easier to access entity values
  $entityform_wrapper = entity_metadata_wrapper('entityform', $entityform);

  if (isset($entityform_wrapper->field_referenced_node)) {
    if ($entityform_wrapper->field_referenced_node->value()->type == 'registration_page') {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Generate markup for the event info for an event on a registration page
 * This should only be called if we're on a registration page
 */
function _registration_pages_get_event_markup($node) {
  // Create an entity_metadata_wrapper to access values
  $node_wrapper = entity_metadata_wrapper('node', $node);
  $event_date = $node_wrapper->field_event_date->value();

  $event_markup = '<p>';

  if (!empty($event_date)) {
    $event_markup .= "<strong>Date:</strong> ";
    $event_markup .= _registration_pages_get_formatted_date_from_field($node->field_event_date, 'value');
    $event_markup .= "<br>";

    $event_markup .= "<strong>Time:</strong> ";
    $event_markup .= _registration_pages_get_formatted_time_from_field($node->field_event_date, 'value');

    // End time
    $event_markup .= _registration_pages_format_end_time($node->field_event_date);

    $event_markup .= "<br>";
  }

  if ($location_text = $node_wrapper->field_location_as_long_text->value()) {
    $event_markup .= '<strong>Location:</strong> ';
    $event_markup .= $location_text;
  }

  $event_markup .=  '</p>';

  return $event_markup;
}

function _registration_pages_format_end_time($field) {
  $markup = '';
  if (isset($field[LANGUAGE_NONE][0]['value2'])) {
    $end_time = _registration_pages_get_formatted_time_from_field($field, 'value2');
    if (_registration_pages_is_multiday_event($field)) {
      $end_day = _registration_pages_get_formatted_date_from_field($field, 'value2');
      $end_time = _registration_pages_get_formatted_time_from_field($field, 'value2');
      $markup .= " - $end_day at $end_time";
    }
    else {
      $markup .= ' - ' . $end_time;
    }
  }
  return $markup;
}
/**
 * Replaces the registration form markup with a message if form is inactive
 */
function _registration_pages_process_registration_period(&$variables) {
  if (_registration_pages_form_is_inactive($variables['node'])) {
    unset($variables['content']['field_registration_form']);
    $variables['content']['field_registration_form']['#markup'] = _registration_pages_get_markup_for_inactive_form($variables['node']);
  }
}

function _registration_pages_is_multiday_event($field) {
  $start_date = date('m/d', strtotime($field[LANGUAGE_NONE][0]['value']));
  $end_date = date('m/d', strtotime($field[LANGUAGE_NONE][0]['value2']));
  return $start_date != $end_date;
}

/**
 * Determines whether a form is active or inactive
 */
function _registration_pages_form_is_inactive($node) {
  if (_registration_pages_form_is_not_yet_live($node) ||_registration_pages_form_deadline_has_passed($node)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Checks whether the form registration start date is in the future
 * @todo Refactor field_event_registration_period into the form itself
 * Since there are other forms with this requirement and its the more appropriate
 * place for that logic to live
 */
function _registration_pages_form_is_not_yet_live($node) {
  if (isset($node->field_event_registration_period[LANGUAGE_NONE][0]['value'])) {
    $today_timestamp = time();
    $golive_timestamp = _registration_pages_get_timestamp_from_field_value($node->field_event_registration_period[LANGUAGE_NONE][0]['value'], $node->field_event_registration_period[LANGUAGE_NONE][0]['timezone_db']);
    if ($today_timestamp < $golive_timestamp) {
      return TRUE;
    }
  }
  return FALSE;
}

/**
 * Checks whether the form registration end date was in the past
 */
function _registration_pages_form_deadline_has_passed($node) {
  if (isset($node->field_event_registration_period[LANGUAGE_NONE][0]['value2'])
      && $node->field_event_registration_period[LANGUAGE_NONE][0]['value'] != $node->field_event_registration_period[LANGUAGE_NONE][0]['value2']) { // Once a value has been set for the end date, removing it apparently sets it equal to the start date in the db
    $today_timestamp = time();
    $deadline_timestamp = _registration_pages_get_timestamp_from_field_value($node->field_event_registration_period[LANGUAGE_NONE][0]['value2'], $node->field_event_registration_period[LANGUAGE_NONE][0]['timezone_db']);
    if ($today_timestamp > $deadline_timestamp) {
      return TRUE;
    }
  }
  return FALSE;
}

/*
  Helper function for creating timestamps from a field value
 */
function _registration_pages_get_timestamp_from_field_value($value, $timezone) {
  return strtotime(
    $value .
    ' ' . $timezone);
}

/**
 * Generates the markup that replaces inactive registration forms
 */
function _registration_pages_get_markup_for_inactive_form($node) {
  $markup = '<p>';
  if (_registration_pages_form_is_not_yet_live($node)) {
    $custom_message_field = $node->field_event_text_before_reg_open;
    $message_intro = 'This form will be available on ';
    $active_date_value_string = 'value';
  }
  elseif (_registration_pages_form_deadline_has_passed($node)) {
    $custom_message_field = $node->field_event_text_after_reg_close;
    $message_intro = 'The deadline for submitting this form was ';
    $active_date_value_string = 'value2';
  }
  // Add the custom message to the markup if appropriate
  if (!empty($custom_message_field)) {
    $markup .= $custom_message_field[LANGUAGE_NONE][0]['value'] . ' ';
  }

  $form_date = _registration_pages_get_formatted_date_from_field($node->field_event_registration_period, $active_date_value_string);
  $form_time = _registration_pages_get_formatted_time_from_field($node->field_event_registration_period, $active_date_value_string);

  $markup .= "$message_intro $form_date at $form_time.";
  $markup .= '</p>';

  return $markup;
}

function _registration_pages_get_formatted_date_from_field($field, $value_string = 'value') {
  $timezone = $field[LANGUAGE_NONE][0]['timezone_db'];
  $value = $field[LANGUAGE_NONE][0][$value_string];
  $timestamp_value = _registration_pages_get_timestamp_from_field_value($value, $timezone);
  return format_date($timestamp_value, 'custom', 'l, F d, Y');
}

function _registration_pages_get_formatted_time_from_field($field, $value_string = 'value') {
  $timezone = $field[LANGUAGE_NONE][0]['timezone_db'];
  $value = $field[LANGUAGE_NONE][0][$value_string];
  $timestamp_value = _registration_pages_get_timestamp_from_field_value($value, $timezone);
  return format_date($timestamp_value, 'custom', 'g:i a');
}
