<?php

/**
 * Implements hook_install()
 * Loops through the roles in the system and creates a test user for that role
 */

function ilr_dev_install() {
  variable_set('site_name','ILR Dev Site');
  variable_set('file_public_path','sites/default/files');
  variable_set('stage_file_proxy_origin','http://www.ilr.cornell.edu');
  variable_set('stage_file_proxy_origin_dir','sites/ilr.cornell.edu/files');
  variable_set('features_rebuild_on_flush',FALSE);
  variable_set('entity_rebuild_on_flush',FALSE);

  // Disable any modules we don't want running locally
  module_disable(array(
    'securepages',
    'memcache',
    'google_analytics_universal',
  ));

  _ilr_dev_add_test_users();
  _ilr_dev_reset_passwords();
}

function _ilr_dev_add_test_users() {
  $users = array();
  $roles = user_roles(true);

  foreach ($roles as $name) {
    $existing_user = user_load_by_name($name);
    if (!$existing_user) {
      $rid = user_role_load_by_name($name)->rid;
      $email = 'test_' . str_replace(' ', '_', $name) . '@cornell.edu';
      $users[] = array(
        'name' => $name,
        'pass' => 'testing',
        'mail' => $email,
        'status' => 1,
        'roles' => array($rid => true),
      );
    }
  }

  if (!empty($users)) {
    foreach ($users as $key => $user) {
      $new_user = user_save((object) $user);
    }
  }
}

/**
 * Since SSL is not enabled on featuretest, we manually update the passwords
 */
function _ilr_dev_reset_passwords() {
  $users = entity_load('user');
  foreach ($users as $user) {
    if (!empty($user->name)) {
      $edit['pass'] = 'testing';
      user_save($user, $edit);
    }
  }
}
