<?php

/**
 * Implements hook_install()
 * Loops through the roles in the system and creates a test user for that role
 */

function ilr_dev_install() {
  variable_set('site_name','ILR Dev Site');
  variable_set('file_public_path','sites/default/files');
  variable_set('stage_file_proxy_origin','http://www.ilr.cornell.edu');
  variable_set('stage_file_proxy_origin_dir','sites/ilr.cornell.edu/files');
  variable_set('features_rebuild_on_flush',FALSE);
  variable_set('entity_rebuild_on_flush',FALSE);

  // Disable any modules we don't want running locally
  module_disable(array(
    'securepages',
    'memcache',
    'google_analytics_universal',
  ));
}
