<?php
/**
 * @file
 * Code for the People Profile Import feature.
 */

include_once 'people_profile_import.features.inc';

/**
 * Implements hook_feeds_plugins()
 */
function people_profile_import_feeds_plugins() {
  $info = array();
  $info['ilr_profiles_feed_xml_parser'] = array(
    'name' => 'People Profiles XML feed parser',
    'description' => 'Imports faculty and staff data from the combined LDAP/Activity Insight XML feed.',
    'help' => '',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'IlrProfilesFeedXmlParser',
      'file' => 'ilr_profiles_feed_xml_parser.inc',
      'path' => drupal_get_path('module', 'people_profile_import') . '/plugins/feeds',
    ),
  );
  return $info;
}

/**
 * Invoked before a feed item is saved.
 *
 * @param $source
 *  FeedsSource object that describes the source that is being imported.
 * @param $entity
 *   The entity object.
 * @param $item
 *   The parser result for this entity.
 */
function people_profile_import_feeds_presave(FeedsSource $source, $entity, $item) {
  // die(print_r($entity));
  // if ($entity->type == 'people_profile' && isset($entity->field_ai_research_statement_short)) {
  //   $entity->field_ai_research_statement['und'][0]['summary'] = $entity->field_ai_research_statement_short['und'][0]['value'];
  //   unset($entity->field_ai_research_statement_short);
  // }
}
