<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'news.features.inc';

/**
 * Implements hook_bean_types_api_info().
 */
function news_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Implements hook_bean_types().
 */
function news_bean_types() {
  $plugins = array();
  $plugins['tagged_news'] = array(
    'label' => t('News Listing (tags)'),
    'description' => t('Provides a listing of news callouts based on callout tags.'),
    'handler' => array(
      'class' => 'TaggedNewsBean',
      'parent' => 'bean',
      'path' => drupal_get_path('module', 'news') . '/plugins/bean',
      'file' => 'tagged_news.inc',
    ),
  );
  return $plugins;
}
