<?php
/**
 * @file
 * Code for the ILR Manual Listing feature.
 */


include_once 'ilr_manual_listing.features.inc';

/**
 * Implements hook_menu().
 */
function ilr_manual_listing_menu() {
  $items = array();
  $items['admin/config/content/manual_listing'] = array(
    'title' => t('Manual Listing Block Settings'),
    'description' => t('Configure content types available to manual listing content blocks'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ilr_manual_listing_admin'),
    'file' => 'includes/ilr_manual_listing.admin.inc',
    'access arguments' => array('administer ilr manual listing configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
/**
 * Implements hook_permission()
 */
function ilr_manual_listing_permission() {
  return array(
    'administer ilr manual listing configuration' => array(
      'title' => t('Administer Manual Listing Blocks'),
      'description' => t('Configure content types available to manual listing blocks.'),
    ),
  );
}

/**
 * Removes partial string matches from listing
 * See views issue at https://www.drupal.org/node/2529372
 * Also orders the results based on the order in the block configuration
 */
function ilr_manual_listing_views_pre_render(&$view) {
  if ($view->name == 'course_manual_listings') {
    $prefix_string = strtolower($view->exposed_data['field_catalog_prefix_value']);
    $prefixes = explode(' ', $prefix_string);
    $ordered_array = array();
    foreach ($view->result as $key => $node) {
      $prefix = strtolower($node->field_field_catalog_prefix[0]['raw']['value']);
      $prefixes_key = array_search($prefix, $prefixes);
      if ($prefixes_key !== FALSE) { // array_search returns the zero-indexed key or FALSE
        $ordered_array[$prefixes_key] = $view->result[$key];
      } else { // It was a partial match, so we can discard it
        unset($view->result[$key]);
      }
    }
    ksort($ordered_array); // Sort the array based on the numerical keys
    $view->result = $ordered_array;
  }
}

function _ilr_manual_listing_default_bundles(){
  return array('youtube_video','news_item', 'workspan');
}
