<?php
/**
 * @file
 * Code for the WIT feature.
 */

include_once 'wit.features.inc';

/**
 * Implements hook_node_update()
 * Checks to see if a WIT article is being published
 *   - publishes all unpublished articles
 *   - todo: send the WIT email
 */
function wit_node_update($node) {
  if($node->type == "wit_article") {
    if ($node->original->status == 0 && $node->status == 1) {
      $article_date = $node->field_published_date['und'][0]['value'];
      _wit_publish_daily_articles($article_date);
    }
  }
}

/**
 * Implements hook_preprocess_hook()
 *
 *  Formats the WIT articles
 */
function wit_preprocess_node(&$variables) {
  if ($variables['type'] == 'wit_article') {
    $variables['content']['link'] = array(
      '#markup' => _wit_build_reference($variables),
      '#weight' => 10,
    );
    // Remove the variables we needed for the reference
    unset($variables['content']['field_article_title']);
    unset($variables['content']['field_website_url']);
    unset($variables['content']['field_author']);
    unset($variables['content']['field_term_publication']);
    unset($variables['content']['field_term_wire_service']);
    unset($variables['content']['field_published_date']);
  }
}

/**
 * Implements hook_node_view()
 *
 *  Alters titles for wit articles since Drupal titles
 *  are limited to 128 characters
 */
function wit_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'wit_article') {
    drupal_set_title($node->field_article_lead_full[LANGUAGE_NONE][0]['safe_value']);
    hide($node->content['field_article_lead_full']);
  }
}

/**
 * Implements hook_menu
 * Defines the WIT RSS Feed Path
 */
function wit_menu() {
  $items = array();
  $items['rss/library/libraryWit.xml'] = array(
    'title' => 'WIT RSS Feed',
    'page callback' => '_wit_rss_feed',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Provides a simple RSS feed
 */
function _wit_rss_feed() {
  $nids = _wit_get_nids();
  $link = url(current_path(), array('absolute' => true));
  $channel = array(
    'title' => t('Workplace Issues Today'),
    'description' => 'WIT is a free alert service, providing abstracts and links to workplace-related news stories covered in the major media.',
    'link' => $link,
  );
  node_feed($nids, $channel);
}

/**
 * Retrieves the specified number of nids
 * for the RSS feed
 */
function _wit_get_nids($count = 15) {
  $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'wit_article')
      ->propertyCondition('status', 1)
      ->fieldOrderBy('field_published_date', 'value', 'DESC')
      ->range(0, $count);

    $result = $query->execute();
    return array_keys($result['node']);
}

/**
 * Custom function to publish all articles for a given day
 *
 */
function _wit_publish_daily_articles($article_date) {
  $query = new EntityFieldQuery();

  $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'wit_article')
    ->propertyCondition('status', 0)
    ->fieldCondition('field_published_date', 'value', $article_date);

  $result = $query->execute();

  if (empty($result)) {
    drupal_set_message(t("Today's WIT articles have been published."), 'status');
  }
  else {
    foreach ($result['node'] as $node) {
      $node = node_load($node->nid, $node->vid);
      $node->status = 1;
      node_save($node);
    }
  }
}

/**
 * Custom function for outputting the article reference
 *
 */
function _wit_build_reference($variables) {
  $title = $variables['field_article_title'][0]['value'];
  $url = (count($variables['field_website_url']))
    ? $variables['field_website_url'][0]['url']
    : '';
  $link = "<a href='{$url}' target='_blank'>{$title}</a>,";
  $author = (count($variables['field_author']) > 0) ? 'by ' . $variables['field_author'][0]['value'] . ',' : '';
  $publication = $variables['field_term_publication'][0]['taxonomy_term']->name . ',';
  $service = (count($variables['field_term_wire_service']) > 0) ? $variables['field_term_wire_service'][0]['taxonomy_term']->name . ',' : '';
  // Convert the Date string to a date object
  $date_object = date_create($variables['field_published_date'][0]['value'], timezone_open('America/New_York'));
  // Format the date object
  $published = date_format($date_object, 'M d Y');
  $reference = "<div class='reference'><p>See \"{$link}\" {$author} {$publication} {$service} {$published}</p></div>";
  return $reference;
}
